// Auto-generated verified community reviews dataset
export interface StaticReviewRecord {
  id: string;
  appId: string;
  appSlug?: string;
  appName?: string;
  userName: string;
  rating: number;
  reviewText: string;
  timestamp: string;
  status: "published" | "pending" | "rejected" | string;
  helpful_count: number;
  isPinned?: boolean;
  reported?: boolean;
  report_count?: number;
  source?: string;
  adminReply?: {
    text: string;
    author: string;
    timestamp: string;
  } | null;
  updated_at?: string;
}

export const STATIC_COMMUNITY_REVIEWS: StaticReviewRecord[] = [
  {
    "id": "rev_1788865608237_640ph",
    "appId": "3h6d8psbv",
    "appSlug": "top-rummy",
    "appName": "TOP RUMMY",
    "userName": "Deepali K.",
    "rating": 3,
    "reviewText": "Decent puzzle game, but I would love to see some more variety in the background music themes to keep things fresh.",
    "timestamp": "2026-09-08T11:06:48.237Z",
    "status": "pending",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:48.237Z"
  },
  {
    "id": "rev_1788865608226_5kju6",
    "appId": "3h6d8psbv",
    "appSlug": "top-rummy",
    "appName": "TOP RUMMY",
    "userName": "Rohit_CardMaster",
    "rating": 4,
    "reviewText": "Solid game mechanics, though the difficulty jump in the boss nodes can be a bit steep sometimes. Still, very fun to play.",
    "timestamp": "2026-09-08T11:06:48.226Z",
    "status": "pending",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:48.226Z"
  },
  {
    "id": "rev_1788865608216_c2g4a",
    "appId": "3h6d8psbv",
    "appSlug": "top-rummy",
    "appName": "TOP RUMMY",
    "userName": "Ananya_Gamer",
    "rating": 4,
    "reviewText": "Good overall experience and definitely keeps my brain active. I do wish there were even more power-ups available in the later stages.",
    "timestamp": "2026-09-08T11:06:48.216Z",
    "status": "pending",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:48.216Z"
  },
  {
    "id": "rev_1788865608205_myrxb",
    "appId": "3h6d8psbv",
    "appSlug": "top-rummy",
    "appName": "TOP RUMMY",
    "userName": "Karthik K.",
    "rating": 5,
    "reviewText": "Absolutely perfect for short bursts of play. Each node only takes a few minutes, which is exactly what I need during breaks.",
    "timestamp": "2026-09-08T11:06:48.205Z",
    "status": "pending",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:48.205Z"
  },
  {
    "id": "rev_1788865608195_hxwaf",
    "appId": "3h6d8psbv",
    "appSlug": "top-rummy",
    "appName": "TOP RUMMY",
    "userName": "Sneha_R",
    "rating": 5,
    "reviewText": "Very polished app. The drag-and-drop interface feels very natural and responsive on my tablet.",
    "timestamp": "2026-09-08T11:06:48.195Z",
    "status": "pending",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:48.195Z"
  },
  {
    "id": "rev_1788865608184_t9e1x",
    "appId": "3h6d8psbv",
    "appSlug": "top-rummy",
    "appName": "TOP RUMMY",
    "userName": "Amit Verma",
    "rating": 5,
    "reviewText": "Three-star mastery is addictive. I spent all night trying to get a perfect score on the latest zone just to unlock those golden card backs.",
    "timestamp": "2026-09-08T11:06:48.184Z",
    "status": "pending",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:48.184Z"
  },
  {
    "id": "rev_1788865608174_45xrf",
    "appId": "3h6d8psbv",
    "appSlug": "top-rummy",
    "appName": "TOP RUMMY",
    "userName": "Priya_M",
    "rating": 5,
    "reviewText": "I appreciate that I can play this offline during my commute. The turn limits make it a much tighter, more tactical game than what I am used to.",
    "timestamp": "2026-09-08T11:06:48.174Z",
    "status": "pending",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:48.174Z"
  },
  {
    "id": "rev_1788865608164_qs5ny",
    "appId": "3h6d8psbv",
    "appSlug": "top-rummy",
    "appName": "TOP RUMMY",
    "userName": "Vikram99",
    "rating": 5,
    "reviewText": "Challenging AI bosses actually make you think! I had to change my strategy multiple times to pass the higher levels. Very engaging experience.",
    "timestamp": "2026-09-08T11:06:48.164Z",
    "status": "pending",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:48.164Z"
  },
  {
    "id": "rev_1788865608153_mjown",
    "appId": "3h6d8psbv",
    "appSlug": "top-rummy",
    "appName": "TOP RUMMY",
    "userName": "Sarah_K",
    "rating": 5,
    "reviewText": "The visuals are top-tier and the animations when you finish a set are so satisfying. It runs perfectly smooth on my OnePlus with zero heating issues.",
    "timestamp": "2026-09-08T11:06:48.153Z",
    "status": "pending",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:48.153Z"
  },
  {
    "id": "rev_1788865608135_zbitr",
    "appId": "3h6d8psbv",
    "appSlug": "top-rummy",
    "appName": "TOP RUMMY",
    "userName": "Kevin D.",
    "rating": 5,
    "reviewText": "Finally, a rummy game that feels like a real puzzle adventure! I love how the campaign map replaces the usual boring menus. It keeps me coming back to unlock new levels.",
    "timestamp": "2026-09-08T11:06:48.135Z",
    "status": "pending",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:48.135Z"
  },
  {
    "id": "rev_1788865562034_nc836",
    "appId": "quyol591v",
    "appSlug": "max-rummy",
    "appName": "MAX RUMMY",
    "userName": "Deepali K.",
    "rating": 4,
    "reviewText": "Clean interface and very responsive touch controls. The cyberpunk vibe is unique and looks great on my screen. Nice work.",
    "timestamp": "2026-09-08T11:06:02.034Z",
    "status": "pending",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:02.034Z"
  },
  {
    "id": "rev_1788865562025_x6eyh",
    "appId": "quyol591v",
    "appSlug": "max-rummy",
    "appName": "MAX RUMMY",
    "userName": "Rohit_CardMaster",
    "rating": 4,
    "reviewText": "Challenging AI and great visuals. The timer makes things intense, which I enjoy. Decent game to keep your mind sharp.",
    "timestamp": "2026-09-08T11:06:02.025Z",
    "status": "pending",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:02.025Z"
  },
  {
    "id": "rev_1788865562016_jpvhf",
    "appId": "quyol591v",
    "appSlug": "max-rummy",
    "appName": "MAX RUMMY",
    "userName": "Sneha_R",
    "rating": 4,
    "reviewText": "The card dealing animation is really cool and fast. It feels like an arcade game. A very polished experience for anyone who enjoys strategy cards.",
    "timestamp": "2026-09-08T11:06:02.016Z",
    "status": "pending",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:02.016Z"
  },
  {
    "id": "rev_1788865562007_8ivrd",
    "appId": "quyol591v",
    "appSlug": "max-rummy",
    "appName": "MAX RUMMY",
    "userName": "Karthik K.",
    "rating": 4,
    "reviewText": "Efficient app size and very smooth gameplay. Even on an older phone, I haven't experienced any lag or crashes. The offline mode is a huge plus for traveling.",
    "timestamp": "2026-09-08T11:06:02.007Z",
    "status": "pending",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:02.007Z"
  },
  {
    "id": "rev_1788865561999_7sji7",
    "appId": "quyol591v",
    "appSlug": "max-rummy",
    "appName": "MAX RUMMY",
    "userName": "Priya_M",
    "rating": 4,
    "reviewText": "Pretty fun game overall. The graphics are top-tier and it feels very modern. I would love to see a few more background themes in future updates.",
    "timestamp": "2026-09-08T11:06:01.999Z",
    "status": "pending",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:01.999Z"
  },
  {
    "id": "rev_1788865561990_ezvm5",
    "appId": "quyol591v",
    "appSlug": "max-rummy",
    "appName": "MAX RUMMY",
    "userName": "Amit Verma",
    "rating": 4,
    "reviewText": "Solid performance and very clean UI. The auto-sort feature works perfectly to save time during those intense rounds. Great for a quick break.",
    "timestamp": "2026-09-08T11:06:01.990Z",
    "status": "pending",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:01.990Z"
  },
  {
    "id": "rev_1788865561977_p7k3y",
    "appId": "quyol591v",
    "appSlug": "max-rummy",
    "appName": "MAX RUMMY",
    "userName": "Ananya_Gamer",
    "rating": 4,
    "reviewText": "I really love the cyberpunk theme. The cards snap into place with a nice mechanical sound. It is a bit fast-paced for me sometimes, but it is a fun challenge.",
    "timestamp": "2026-09-08T11:06:01.977Z",
    "status": "pending",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:01.977Z"
  },
  {
    "id": "rev_1788865561969_tc8fj",
    "appId": "quyol591v",
    "appSlug": "max-rummy",
    "appName": "MAX RUMMY",
    "userName": "Vikram99",
    "rating": 4,
    "reviewText": "The AI is surprisingly challenging and actually makes me think about my discards. Runs perfectly on my device without any overheating issues. Good job on the optimization.",
    "timestamp": "2026-09-08T11:06:01.969Z",
    "status": "pending",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:01.969Z"
  },
  {
    "id": "rev_1788865561960_h90xs",
    "appId": "quyol591v",
    "appSlug": "max-rummy",
    "appName": "MAX RUMMY",
    "userName": "Sarah_K",
    "rating": 5,
    "reviewText": "Finally, a rummy app that doesn't drag on forever. The overdrive pacing is exactly what I was looking for. Everything is snappy and the synth-wave music keeps the energy high.",
    "timestamp": "2026-09-08T11:06:01.960Z",
    "status": "pending",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:01.960Z"
  },
  {
    "id": "rev_1788865561951_3kor6",
    "appId": "quyol591v",
    "appSlug": "max-rummy",
    "appName": "MAX RUMMY",
    "userName": "Kevin D.",
    "rating": 5,
    "reviewText": "Absolutely hooked on the neon aesthetic! It is a complete departure from the usual boring card apps, and the particle effects when you win are just so satisfying. Highly recommend.",
    "timestamp": "2026-09-08T11:06:01.951Z",
    "status": "pending",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:06:01.951Z"
  },
  {
    "id": "rev_1788865534086_ewptb",
    "appId": "rer0jsbkw",
    "appSlug": "rumble-rummy",
    "appName": "RUMBLE RUMMY",
    "userName": "Deepali K.",
    "rating": 3,
    "reviewText": "It’s a decent time-killer, though the matchmaking can sometimes feel a bit repetitive. Good for short breaks, though.",
    "timestamp": "2026-09-08T11:05:34.086Z",
    "status": "pending",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:34.086Z"
  },
  {
    "id": "rev_1788865534078_ygj1j",
    "appId": "rer0jsbkw",
    "appSlug": "rumble-rummy",
    "appName": "RUMBLE RUMMY",
    "userName": "Rohit_CardMaster",
    "rating": 3,
    "reviewText": "The game logic is sound, but the animations feel a little sparse. It's functional, but maybe could use a bit more visual flair.",
    "timestamp": "2026-09-08T11:05:34.078Z",
    "status": "pending",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:34.078Z"
  },
  {
    "id": "rev_1788865534070_q8dr4",
    "appId": "rer0jsbkw",
    "appSlug": "rumble-rummy",
    "appName": "RUMBLE RUMMY",
    "userName": "Ananya_Gamer",
    "rating": 4,
    "reviewText": "Clean interface and very responsive controls. Would love to see an option for landscape mode in a future update.",
    "timestamp": "2026-09-08T11:05:34.070Z",
    "status": "pending",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:34.070Z"
  },
  {
    "id": "rev_1788865534061_f26lv",
    "appId": "rer0jsbkw",
    "appSlug": "rumble-rummy",
    "appName": "RUMBLE RUMMY",
    "userName": "Karthik K.",
    "rating": 4,
    "reviewText": "The 12-second timer is a bit intense for casual play, but it definitely keeps the game moving fast as advertised.",
    "timestamp": "2026-09-08T11:05:34.061Z",
    "status": "pending",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:34.061Z"
  },
  {
    "id": "rev_1788865534048_mi64o",
    "appId": "rer0jsbkw",
    "appSlug": "rumble-rummy",
    "appName": "RUMBLE RUMMY",
    "userName": "Sneha_R",
    "rating": 4,
    "reviewText": "Really solid gameplay loop. My only suggestion would be to add a few more background music tracks to choose from.",
    "timestamp": "2026-09-08T11:05:34.048Z",
    "status": "pending",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:34.048Z"
  },
  {
    "id": "rev_1788865534038_cbjst",
    "appId": "rer0jsbkw",
    "appSlug": "rumble-rummy",
    "appName": "RUMBLE RUMMY",
    "userName": "Amit Verma",
    "rating": 5,
    "reviewText": "Super crisp sound effects when you snap a card from the discard pile. Feels very tactile and satisfying.",
    "timestamp": "2026-09-08T11:05:34.038Z",
    "status": "pending",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:34.038Z"
  },
  {
    "id": "rev_1788865534029_h9m7r",
    "appId": "rer0jsbkw",
    "appSlug": "rumble-rummy",
    "appName": "RUMBLE RUMMY",
    "userName": "Priya_M",
    "rating": 5,
    "reviewText": "I adore the offline mode. It’s my go-to game whenever I'm on a flight and need something to keep my brain sharp.",
    "timestamp": "2026-09-08T11:05:34.029Z",
    "status": "pending",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:34.029Z"
  },
  {
    "id": "rev_1788865534021_anrmo",
    "appId": "rer0jsbkw",
    "appSlug": "rumble-rummy",
    "appName": "RUMBLE RUMMY",
    "userName": "Vikram99",
    "rating": 5,
    "reviewText": "Runs perfectly on my OnePlus without any heating issues. The arcade-saloon aesthetic is a really nice touch compared to the standard green tables.",
    "timestamp": "2026-09-08T11:05:34.021Z",
    "status": "pending",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:34.021Z"
  },
  {
    "id": "rev_1788865534012_stahd",
    "appId": "rer0jsbkw",
    "appSlug": "rumble-rummy",
    "appName": "RUMBLE RUMMY",
    "userName": "Sarah_K",
    "rating": 5,
    "reviewText": "The Rumble mechanic adds such a fun layer of strategy. Love how the cards automatically sort themselves so I can focus on my discards.",
    "timestamp": "2026-09-08T11:05:34.012Z",
    "status": "pending",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:34.012Z"
  },
  {
    "id": "rev_1788865534004_ywf20",
    "appId": "rer0jsbkw",
    "appSlug": "rumble-rummy",
    "appName": "RUMBLE RUMMY",
    "userName": "Kevin D.",
    "rating": 5,
    "reviewText": "Finally, a rummy app that doesn't waste my time with endless menus. The 1v1 pace is perfect for my morning commute.",
    "timestamp": "2026-09-08T11:05:34.004Z",
    "status": "pending",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:34.004Z"
  },
  {
    "id": "rev_1788865523517_aogxu",
    "appId": "fuma9mbmc",
    "appSlug": "rummy-888",
    "appName": "RUMMY 888",
    "userName": "Deepali K.",
    "rating": 3,
    "reviewText": "Decent experience, but I had some trouble with the tutorial steps. Could be simplified a bit for new players.",
    "timestamp": "2026-09-08T11:05:23.517Z",
    "status": "pending",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:23.517Z"
  },
  {
    "id": "rev_1788865523508_tmicy",
    "appId": "fuma9mbmc",
    "appSlug": "rummy-888",
    "appName": "RUMMY 888",
    "userName": "Rohit_CardMaster",
    "rating": 3,
    "reviewText": "It is an okay app. The graphics are nice, but I find the AI a bit predictable after playing for a few hours.",
    "timestamp": "2026-09-08T11:05:23.508Z",
    "status": "pending",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:23.508Z"
  },
  {
    "id": "rev_1788865523500_cp3hg",
    "appId": "fuma9mbmc",
    "appSlug": "rummy-888",
    "appName": "RUMMY 888",
    "userName": "Ananya_Gamer",
    "rating": 3,
    "reviewText": "The game logic is sound, but the pace is a bit fast for me. I think the timer could be adjusted to be more beginner-friendly.",
    "timestamp": "2026-09-08T11:05:23.500Z",
    "status": "pending",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:23.500Z"
  },
  {
    "id": "rev_1788865523491_yxh4f",
    "appId": "fuma9mbmc",
    "appSlug": "rummy-888",
    "appName": "RUMMY 888",
    "userName": "Karthik K.",
    "rating": 4,
    "reviewText": "Great for practicing sequences. The difficulty scales well, though I wish the discard pile navigation was a bit larger on smaller screens.",
    "timestamp": "2026-09-08T11:05:23.491Z",
    "status": "pending",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:23.491Z"
  },
  {
    "id": "rev_1788865523480_vdklc",
    "appId": "fuma9mbmc",
    "appSlug": "rummy-888",
    "appName": "RUMMY 888",
    "userName": "Sneha_R",
    "rating": 4,
    "reviewText": "Very polished interface. It loads instantly and I haven't experienced any bugs or crashes so far. Good work.",
    "timestamp": "2026-09-08T11:05:23.481Z",
    "status": "pending",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:23.481Z"
  },
  {
    "id": "rev_1788865523472_1jm9r",
    "appId": "fuma9mbmc",
    "appSlug": "rummy-888",
    "appName": "RUMMY 888",
    "userName": "Amit Verma",
    "rating": 4,
    "reviewText": "Solid gameplay and the AI provides a good challenge. Would give five stars if there were even more table themes to choose from.",
    "timestamp": "2026-09-08T11:05:23.472Z",
    "status": "pending",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:23.472Z"
  },
  {
    "id": "rev_1788865523463_btpit",
    "appId": "fuma9mbmc",
    "appSlug": "rummy-888",
    "appName": "RUMMY 888",
    "userName": "Priya_M",
    "rating": 5,
    "reviewText": "Stunning visuals and the animations when winning a hand are so satisfying. Highly recommend for a relaxing evening.",
    "timestamp": "2026-09-08T11:05:23.463Z",
    "status": "pending",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:23.463Z"
  },
  {
    "id": "rev_1788865523455_adn1v",
    "appId": "fuma9mbmc",
    "appSlug": "rummy-888",
    "appName": "RUMMY 888",
    "userName": "Vikram99",
    "rating": 5,
    "reviewText": "Best card app I have downloaded. The offline mode is super reliable for when I am commuting and have no signal.",
    "timestamp": "2026-09-08T11:05:23.455Z",
    "status": "pending",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:23.455Z"
  },
  {
    "id": "rev_1788865523446_r6n79",
    "appId": "fuma9mbmc",
    "appSlug": "rummy-888",
    "appName": "RUMMY 888",
    "userName": "Sarah_K",
    "rating": 5,
    "reviewText": "The auto-group feature is a game changer. It saves so much time and lets me focus entirely on my strategy during intense matches.",
    "timestamp": "2026-09-08T11:05:23.446Z",
    "status": "pending",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:23.446Z"
  },
  {
    "id": "rev_1788865523437_8clq9",
    "appId": "fuma9mbmc",
    "appSlug": "rummy-888",
    "appName": "RUMMY 888",
    "userName": "Kevin D.",
    "rating": 5,
    "reviewText": "Absolutely love the gold-and-black aesthetic. It feels very premium and runs perfectly smooth on my device without any battery drain.",
    "timestamp": "2026-09-08T11:05:23.437Z",
    "status": "pending",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:23.437Z"
  },
  {
    "id": "rev_1788865503800_y8v6t",
    "appId": "pdwnq0nu8",
    "appSlug": "boss-rummy",
    "appName": "BOSS RUMMY",
    "userName": "Deepali K.",
    "rating": 4,
    "reviewText": "Good overall experience and very well optimized. The turn timer is a little fast for new players, but otherwise, it is a great way to pass the time.",
    "timestamp": "2026-09-08T11:05:03.801Z",
    "status": "pending",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:03.801Z"
  },
  {
    "id": "rev_1788865503791_4lx0d",
    "appId": "pdwnq0nu8",
    "appSlug": "boss-rummy",
    "appName": "BOSS RUMMY",
    "userName": "Amit Verma",
    "rating": 4,
    "reviewText": "Solid gameplay and very stable. My only feedback is that I would love to see a few more card back designs in the shop.",
    "timestamp": "2026-09-08T11:05:03.791Z",
    "status": "pending",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:03.791Z"
  },
  {
    "id": "rev_1788865503782_iye2z",
    "appId": "pdwnq0nu8",
    "appSlug": "boss-rummy",
    "appName": "BOSS RUMMY",
    "userName": "Sneha_R",
    "rating": 5,
    "reviewText": "Impressive! Loving the lounge jazz music and the overall premium vibe of the lobby.",
    "timestamp": "2026-09-08T11:05:03.782Z",
    "status": "pending",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:03.782Z"
  },
  {
    "id": "rev_1788865503773_qe4ro",
    "appId": "pdwnq0nu8",
    "appSlug": "boss-rummy",
    "appName": "BOSS RUMMY",
    "userName": "Rohit_CardMaster",
    "rating": 5,
    "reviewText": "Smooth interface and very clean design. I appreciate how quickly the game loads and the lack of intrusive elements.",
    "timestamp": "2026-09-08T11:05:03.773Z",
    "status": "pending",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:03.773Z"
  },
  {
    "id": "rev_1788865503760_kavla",
    "appId": "pdwnq0nu8",
    "appSlug": "boss-rummy",
    "appName": "BOSS RUMMY",
    "userName": "Ananya_Gamer",
    "rating": 5,
    "reviewText": "The Boss Tournament mode is excellent. The unique house rules really force you to change your strategy on the fly.",
    "timestamp": "2026-09-08T11:05:03.760Z",
    "status": "pending",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:03.760Z"
  },
  {
    "id": "rev_1788865503751_mczrl",
    "appId": "pdwnq0nu8",
    "appSlug": "boss-rummy",
    "appName": "BOSS RUMMY",
    "userName": "Karthik K.",
    "rating": 5,
    "reviewText": "Those golden flair animations when you declare a winning hand are so satisfying. It feels like a high-end experience.",
    "timestamp": "2026-09-08T11:05:03.751Z",
    "status": "pending",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:03.751Z"
  },
  {
    "id": "rev_1788865503736_vc7as",
    "appId": "pdwnq0nu8",
    "appSlug": "boss-rummy",
    "appName": "BOSS RUMMY",
    "userName": "Priya_M",
    "rating": 5,
    "reviewText": "Finally, a polished app that does not stutter or lag. Everything runs so smoothly on my device, even during long tournament rounds.",
    "timestamp": "2026-09-08T11:05:03.736Z",
    "status": "pending",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:03.736Z"
  },
  {
    "id": "rev_1788865503727_jon99",
    "appId": "pdwnq0nu8",
    "appSlug": "boss-rummy",
    "appName": "BOSS RUMMY",
    "userName": "Vikram99",
    "rating": 5,
    "reviewText": "The AI is actually smart! No two opponents play the same way, which keeps the challenge fresh every single time I open the app.",
    "timestamp": "2026-09-08T11:05:03.727Z",
    "status": "pending",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:03.727Z"
  },
  {
    "id": "rev_1788865503718_raka6",
    "appId": "pdwnq0nu8",
    "appSlug": "boss-rummy",
    "appName": "BOSS RUMMY",
    "userName": "Sarah_K",
    "rating": 5,
    "reviewText": "Fantastic graphics and the haptic feedback when a meld is formed feels incredibly tactile. Best card game on my phone right now.",
    "timestamp": "2026-09-08T11:05:03.718Z",
    "status": "pending",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:03.718Z"
  },
  {
    "id": "rev_1788865503709_zeh2p",
    "appId": "pdwnq0nu8",
    "appSlug": "boss-rummy",
    "appName": "BOSS RUMMY",
    "userName": "Kevin D.",
    "rating": 5,
    "reviewText": "The tycoon progression system is a total game changer. I love upgrading my virtual office as I win matches. It makes the whole experience feel like I am building something.",
    "timestamp": "2026-09-08T11:05:03.709Z",
    "status": "pending",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-08T11:05:03.709Z"
  }
];
