// No secureStorage import to avoid Vercel build errors when secureStorage is stripped

export interface Banner {
  id: string;
  title: string;
  subtitle: string;
  image: string;
  link: string;
}

export interface GlobalSettings {
  site_title: string;
  meta_description: string;
  logo_url: string;
  favicon_url: string;
  helpline_whatsapp: string;
  helpline_telegram: string;
  support_email: string;
  disclaimer_text: string;
  disclaimer_heading?: string;
  ethics_discrimination_text: string;
  ethics_heading?: string;
  portal_heading?: string;
  important_notice_heading?: string;
  ticker_text: string;
  animations_enabled: boolean;
  seo_keywords?: string;
  about_content?: string;
  contact_content?: string;
  privacy_content?: string;
  terms_content?: string;
  responsibility_content?: string;
  important_notice?: string;
  categories: string[];
  banners: Banner[];
  last_updated?: string;
  secure_index_title?: string;
  secure_index_subtitle?: string;
  trending_searches?: string[];
  hero_title_text?: string;
  hero_title_color?: string;
  hero_title_style?: string;
  hero_title_animation?: string;
  hero_title_subtitle?: string;
  hero_title_visible?: boolean;
  ga_tracking_id?: string;
  quick_links?: Array<{ title: string; subtitle?: string; icon?: string; color?: string; url: string }>;
  social_links?: { facebook?: string; instagram?: string; twitter?: string; linkedin?: string; youtube?: string; };
  website_faqs?: Array<{ question: string; answer: string }>;
  developers?: Array<{ name: string; role: string; bio?: string; image_url?: string; github?: string; twitter?: string; avatar_url?: string; social?: any }>;
}

export interface NewsItem {
  id: string;
  slug: string;
  title: string;
  logo_url: string;
  description: string;
  ceo_name: string;
  ceo_description: string;
  seo_title: string;
  seo_description: string;
  seo_keywords?: string;
  category?: string;
  og_image_url?: string;
  canonical_url?: string;
  target_region?: string;
  content: string;
  published_at?: string;
  link: string;
  read_time?: string;
  author?: string;
  description_html?: string;
  date?: string;
  tags?: string[];
}

export interface AppConfig {
  id: string;
  name: string;
  slug: string;
  seo_title?: string;
  seo_description?: string;
  seo_keywords?: string;
  og_image_url?: string;
  canonical_url?: string;
  target_region?: string;
  category: string;
  is_coming_soon?: boolean;
  publish_date?: string;
  version: string;
  file_size: string;
  developer: string;
  icon_url: string;
  screenshots: string[];
  description_html: string;
  red_box_msg: string;
  yellow_box_msg: string;
  idea_box_msg: string;
  safety_status: 'Verified' | 'Caution' | 'Unsafe';
  serial_number: number;
  is_featured: boolean;
  is_new: boolean;
  release_notes: string;
  rating: number;
  created_at: string;
  custom_admin_box_html?: string;
  custom_admin_box_heading?: string;
  features_html?: string;
  faqs?: {question: string; answer: string}[];
  link_configured?: boolean;
  
  video_url?: string;
  is_top_chart?: boolean;
  top_chart_category?: string;
  more_information_url?: string;
}

export interface Review {
  id: string;
  app_id: string;
  username: string;
  rating: number;
  comment: string;
  is_approved: boolean;
}

export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  content: string;
  author: string;
  cover_url: string;
  published_at: string;
  related_app_slug?: string;
  related_app_name?: string;
  seo_title?: string;
  seo_description?: string;
  seo_keywords?: string;
  canonical_url?: string;
  target_region?: string;
  description?: string;
  description_html?: string;
  date?: string;
  thumbnail_url?: string;
  publish_date?: string;
  read_time?: string;
  tags?: string[];
  created_at?: string;
}

export interface NewsUpdate {
  id: string;
  title: string;
  content_html: string;
  category: string;
  published_at: string;
}

export interface VideoItem {
  id: string;
  slug: string;
  title: string;
  description: string;
  youtube_url: string;
  seo_title: string;
  seo_description: string;
  seo_keywords?: string;
  created_at: string;
}

export const mockApps: AppConfig[] = [
  {
    "link_configured": true,
    "is_top_chart": true,
    "version": "2.0.6",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "file_size": "45",
    "created_at": "2026-05-19T12:43:59.040Z",
    "category": "Yono, All App",
    "seo_description": "",
    "slug": "spin-crush-",
    "is_coming_soon": false,
    "custom_admin_box_html": "",
    "safety_status": "Verified",
    "target_region": "",
    "idea_box_msg": "",
    "id": "q82dbbwh4",
    "seo_title": "",
    "is_new": true,
    "features_html": "",
    "red_box_msg": "",
    "release_notes": "",
    "canonical_url": "",
    "name": "SPIN CRUSH ",
    "serial_number": 2,
    "faqs": [],
    "custom_admin_box_heading": "",
    "developer": "Bingo ",
    "og_image_url": "",
    "screenshots": [],
    "is_featured": false,
    "rating": 5,
    "video_url": "",
    "icon_url": "https://res.cloudinary.com/dq34n0ncz/image/upload/f_auto,q_auto/1000119573_wzwse4",
    "yellow_box_msg": "",
    "is_hot": false
  },
  {
    "created_at": "2026-05-19T19:04:26.373Z",
    "file_size": "56",
    "category": "Yono, All App",
    "link_configured": false,
    "version": "1.20.1",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "is_coming_soon": false,
    "custom_admin_box_html": "",
    "safety_status": "Verified",
    "target_region": "",
    "idea_box_msg": "",
    "id": "31og4l26i",
    "seo_title": "",
    "is_new": false,
    "seo_description": "",
    "slug": "yono-arcade",
    "canonical_url": "",
    "name": "YONO ARCADE",
    "serial_number": 3,
    "faqs": [],
    "custom_admin_box_heading": "",
    "features_html": "",
    "release_notes": "",
    "red_box_msg": "",
    "rating": 3.4,
    "video_url": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/67a16d31-6771-4617-b88b-288db51d321d/-/preview/554x554/",
    "yellow_box_msg": "",
    "developer": "Arcade ",
    "og_image_url": "",
    "screenshots": [],
    "is_featured": false
  },
  {
    "category": "Yono, All App",
    "created_at": "2026-05-19T19:23:07.133Z",
    "file_size": "56",
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "version": "1.20.1",
    "link_configured": true,
    "is_new": true,
    "seo_title": "",
    "id": "s5u553ymi",
    "idea_box_msg": "",
    "target_region": "",
    "custom_admin_box_html": "",
    "safety_status": "Verified",
    "is_coming_soon": false,
    "slug": "jaiho-91",
    "seo_description": "",
    "faqs": [],
    "custom_admin_box_heading": "",
    "serial_number": 3,
    "name": "JAIHO 91",
    "canonical_url": "",
    "red_box_msg": "",
    "release_notes": "",
    "features_html": "",
    "yellow_box_msg": "",
    "icon_url": "https://res.cloudinary.com/dyigysy26/image/upload/f_auto,q_auto/1000119609_fkc9fm",
    "video_url": "",
    "rating": 4.8,
    "is_featured": false,
    "screenshots": [],
    "og_image_url": "",
    "developer": "Jaiho"
  },
  {
    "target_region": "",
    "id": "awus3qajs",
    "idea_box_msg": "",
    "seo_title": "",
    "is_new": false,
    "is_coming_soon": false,
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "slug": "bingo-101",
    "seo_description": "",
    "category": "Yono, All App",
    "file_size": "71",
    "created_at": "2026-05-20T03:09:33.880Z",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "link_configured": true,
    "version": "2.5V",
    "yellow_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/d3f6486a-b216-4582-b15d-0c735ff6b08f/-/preview/554x554/",
    "rating": 3.6,
    "video_url": "",
    "og_image_url": "",
    "screenshots": [],
    "is_featured": false,
    "developer": "Bingo",
    "serial_number": 5,
    "custom_admin_box_heading": "",
    "faqs": [],
    "canonical_url": "",
    "name": "BINGO 101",
    "features_html": "",
    "red_box_msg": "",
    "release_notes": ""
  },
  {
    "features_html": "",
    "release_notes": "",
    "red_box_msg": "",
    "faqs": [],
    "custom_admin_box_heading": "",
    "serial_number": 6,
    "canonical_url": "",
    "name": "OK RUMMY",
    "is_featured": false,
    "og_image_url": "",
    "screenshots": [],
    "developer": "Bingo ",
    "icon_url": "https://13eehe59cj.ucarecd.net/97512d34-f561-4ede-8517-2112440079eb/-/preview/554x554/",
    "yellow_box_msg": "",
    "video_url": "",
    "rating": 3,
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "version": "8.3.06.",
    "link_configured": true,
    "category": "Yono, All App",
    "file_size": "67",
    "created_at": "2026-05-20T03:50:33.674Z",
    "slug": "ok-rummy",
    "seo_description": "",
    "seo_title": "",
    "is_new": false,
    "target_region": "",
    "idea_box_msg": "",
    "id": "0uiuuhdrj",
    "is_coming_soon": false,
    "safety_status": "Verified",
    "custom_admin_box_html": ""
  },
  {
    "is_coming_soon": false,
    "custom_admin_box_html": "",
    "safety_status": "Verified",
    "seo_title": "",
    "is_new": false,
    "target_region": "",
    "id": "4yt0f4yd0",
    "idea_box_msg": "",
    "seo_description": "",
    "slug": "jaiho-slots",
    "file_size": "70",
    "created_at": "2026-05-20T03:53:24.482Z",
    "category": "Yono, All App",
    "version": "4.3",
    "link_configured": true,
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "video_url": "",
    "rating": 4.9,
    "yellow_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/2dfe5d55-7896-4f96-8f2b-132190e44f6f/-/preview/540x540/",
    "developer": "Jaiho",
    "is_featured": false,
    "og_image_url": "",
    "screenshots": [],
    "canonical_url": "",
    "name": "JAIHO SLOTS",
    "faqs": [],
    "custom_admin_box_heading": "",
    "serial_number": 7,
    "features_html": "",
    "red_box_msg": "",
    "release_notes": ""
  },
  {
    "seo_description": "",
    "slug": "boss-rummy",
    "is_coming_soon": false,
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "seo_title": "",
    "is_new": false,
    "target_region": "",
    "id": "9r044fyi0",
    "idea_box_msg": "",
    "version": "2.5V",
    "link_configured": true,
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "created_at": "2026-05-20T03:56:42.075Z",
    "file_size": "54",
    "category": "Yono, All App",
    "developer": "Arcade ",
    "is_featured": false,
    "og_image_url": "",
    "screenshots": [],
    "video_url": "",
    "rating": 4.1,
    "icon_url": "https://13eehe59cj.ucarecd.net/b5e9d896-71e8-49d6-b091-a971871161e0/-/preview/1000x1000/",
    "yellow_box_msg": "",
    "features_html": "",
    "red_box_msg": "",
    "release_notes": "",
    "canonical_url": "",
    "name": "BOSS RUMMY",
    "faqs": [],
    "custom_admin_box_heading": "",
    "serial_number": 8
  },
  {
    "link_configured": true,
    "version": "2.0.6",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "created_at": "2026-05-20T04:01:04.611Z",
    "file_size": "79",
    "category": "All App",
    "seo_description": "",
    "slug": "rummy-91",
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "is_coming_soon": false,
    "idea_box_msg": "",
    "id": "5b7fj0cq7",
    "target_region": "",
    "is_new": false,
    "seo_title": "",
    "red_box_msg": "",
    "release_notes": "",
    "features_html": "",
    "name": "RUMMY 91",
    "canonical_url": "",
    "serial_number": 9,
    "custom_admin_box_heading": "",
    "faqs": [],
    "developer": "Addi",
    "screenshots": [],
    "og_image_url": "",
    "is_featured": false,
    "rating": 4.9,
    "video_url": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/393c07ea-4f5e-43a9-ab0c-e12dfe7d755a/-/preview/474x474/",
    "yellow_box_msg": ""
  },
  {
    "faqs": [],
    "custom_admin_box_heading": "",
    "serial_number": 10,
    "canonical_url": "",
    "name": "GOGO RUMMY ",
    "features_html": "",
    "release_notes": "",
    "red_box_msg": "",
    "yellow_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/0d710f11-2c9d-4312-89de-be65ce21a4fe/-/preview/750x750/",
    "video_url": "",
    "rating": 3.9,
    "is_featured": false,
    "og_image_url": "",
    "screenshots": [],
    "developer": "Sk varba",
    "category": "Yono, All App",
    "file_size": "65",
    "created_at": "2026-05-20T06:58:27.643Z",
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "version": "5.0",
    "link_configured": true,
    "seo_title": "",
    "is_new": false,
    "target_region": "",
    "id": "ieam3hkbq",
    "idea_box_msg": "",
    "is_coming_soon": false,
    "custom_admin_box_html": "",
    "safety_status": "Verified",
    "slug": "gogo-rummy-",
    "seo_description": ""
  },
  {
    "created_at": "2026-05-20T08:02:40.971Z",
    "file_size": "75",
    "category": "Yono, All App",
    "version": "1.8",
    "link_configured": true,
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "is_coming_soon": false,
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "seo_title": "",
    "is_new": false,
    "target_region": "",
    "idea_box_msg": "",
    "id": "5j5b7qbrw",
    "seo_description": "",
    "slug": "club-inr",
    "canonical_url": "",
    "name": "CLUB INR",
    "custom_admin_box_heading": "",
    "faqs": [],
    "serial_number": 11,
    "features_html": "",
    "red_box_msg": "",
    "release_notes": "",
    "video_url": "",
    "rating": 4.6,
    "yellow_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/3059d25d-1497-4cff-aead-68758187fe0b/-/preview/554x554/",
    "developer": "S.A vejay",
    "is_featured": false,
    "og_image_url": "",
    "screenshots": []
  },
  {
    "is_coming_soon": false,
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "target_region": "",
    "idea_box_msg": "",
    "id": "f4ktp4dfi",
    "seo_title": "",
    "is_new": false,
    "seo_description": "",
    "slug": "abc-rummy-",
    "created_at": "2026-05-26T07:04:36.330Z",
    "file_size": "61",
    "category": "Yono, All App",
    "link_configured": true,
    "version": "1.8",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "rating": 3.9,
    "video_url": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/f7108631-b74a-49e5-8abf-37cec6950f7c/-/preview/512x512/",
    "yellow_box_msg": "",
    "developer": "Addi",
    "og_image_url": "",
    "screenshots": [],
    "is_featured": false,
    "canonical_url": "",
    "name": "ABC Rummy ",
    "serial_number": 12,
    "faqs": [],
    "custom_admin_box_heading": "",
    "features_html": "",
    "red_box_msg": "",
    "release_notes": ""
  },
  {
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "is_coming_soon": false,
    "id": "4w1yxs6mm",
    "idea_box_msg": "",
    "target_region": "",
    "is_new": false,
    "seo_title": "",
    "seo_description": "",
    "slug": "777-rummy",
    "created_at": "2026-05-26T07:09:01.068Z",
    "file_size": "54",
    "category": "Yono, All App",
    "link_configured": true,
    "version": "1.6",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "rating": 5,
    "video_url": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/fb951184-b849-4ff0-8882-a4d826508fb7/-/preview/190x190/",
    "yellow_box_msg": "",
    "developer": "AB Arora",
    "screenshots": [],
    "og_image_url": "",
    "is_featured": false,
    "name": "777.Rummy",
    "canonical_url": "",
    "serial_number": 13,
    "faqs": [],
    "custom_admin_box_heading": "",
    "red_box_msg": "",
    "release_notes": "",
    "features_html": ""
  },
  {
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "is_coming_soon": false,
    "id": "w1sttlwv7",
    "idea_box_msg": "",
    "target_region": "",
    "is_new": false,
    "seo_title": "",
    "seo_description": "",
    "slug": "ever-777",
    "file_size": "59",
    "created_at": "2026-05-26T07:12:55.821Z",
    "category": "Yono, All App",
    "link_configured": true,
    "version": "1.8",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "rating": 4,
    "video_url": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/74347710-3cb2-468c-98eb-5666a0af487c/-/preview/190x190/",
    "yellow_box_msg": "",
    "developer": "AZ ever",
    "screenshots": [],
    "og_image_url": "",
    "is_featured": false,
    "name": "EVER 777",
    "canonical_url": "",
    "serial_number": 14,
    "faqs": [],
    "custom_admin_box_heading": "",
    "red_box_msg": "",
    "release_notes": "",
    "features_html": ""
  },
  {
    "screenshots": [],
    "og_image_url": "",
    "is_featured": false,
    "developer": "Raj dav",
    "yellow_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/4b2bd57d-9855-40a8-b452-34edee84ed09/-/preview/190x190/",
    "rating": 4,
    "video_url": "",
    "release_notes": "",
    "red_box_msg": "",
    "features_html": "",
    "serial_number": 15,
    "custom_admin_box_heading": "",
    "faqs": [],
    "name": "Game Rummy",
    "canonical_url": "",
    "slug": "game-rummy",
    "seo_description": "",
    "idea_box_msg": "",
    "id": "dp2lcn2ae",
    "target_region": "",
    "is_new": false,
    "seo_title": "",
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "is_coming_soon": false,
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "link_configured": true,
    "version": "2.0",
    "category": "Yono, All App",
    "file_size": "75",
    "created_at": "2026-05-26T07:16:08.600Z"
  },
  {
    "release_notes": "",
    "red_box_msg": "",
    "features_html": "",
    "custom_admin_box_heading": "",
    "faqs": [],
    "serial_number": 16,
    "name": "Hi Rummy ",
    "canonical_url": "",
    "is_featured": false,
    "screenshots": [],
    "og_image_url": "",
    "developer": "Addi",
    "icon_url": "https://13eehe59cj.ucarecd.net/c01e9676-e748-4342-9ac7-e972030981fc/-/preview/190x190/",
    "yellow_box_msg": "",
    "video_url": "",
    "rating": 4.1,
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "version": "1.9",
    "link_configured": true,
    "category": "Yono, All App",
    "file_size": "54",
    "created_at": "2026-05-26T07:18:29.456Z",
    "slug": "hi-rummy-",
    "seo_description": "",
    "is_new": false,
    "seo_title": "",
    "id": "4lgypb90h",
    "idea_box_msg": "",
    "target_region": "",
    "custom_admin_box_html": "",
    "safety_status": "Verified",
    "is_coming_soon": false
  },
  {
    "category": "Yono, All App",
    "file_size": "79",
    "created_at": "2026-05-26T07:21:55.085Z",
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "version": "3.0",
    "link_configured": true,
    "seo_title": "",
    "is_new": false,
    "is_hot": false,
    "target_region": "",
    "idea_box_msg": "",
    "id": "2f90a87hv",
    "is_coming_soon": false,
    "custom_admin_box_html": "",
    "safety_status": "Verified",
    "slug": "inr-rummy",
    "seo_description": "",
    "custom_admin_box_heading": "",
    "faqs": [],
    "serial_number": 17,
    "canonical_url": "",
    "name": "INR Rummy",
    "features_html": "",
    "release_notes": "",
    "red_box_msg": "",
    "yellow_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/2a718650-0602-495f-9ca4-b13c86e58c02/-/preview/190x190/",
    "video_url": "",
    "rating": 5,
    "is_featured": false,
    "og_image_url": "",
    "screenshots": [],
    "developer": "Arcade "
  },
  {
    "serial_number": 18,
    "custom_admin_box_heading": "",
    "faqs": [],
    "canonical_url": "",
    "name": "JAIHO RUMMY ",
    "features_html": "",
    "release_notes": "",
    "red_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/c693366d-d543-4d76-84ba-3963a3f3c792/-/preview/190x190/",
    "yellow_box_msg": "",
    "rating": 3.9,
    "video_url": "",
    "og_image_url": "",
    "screenshots": [],
    "is_featured": false,
    "developer": "PW sahar",
    "category": "Yono, All App",
    "created_at": "2026-05-26T07:26:42.606Z",
    "file_size": "2.4",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "link_configured": true,
    "version": "2.1",
    "target_region": "",
    "id": "9a05609sb",
    "idea_box_msg": "",
    "seo_title": "",
    "is_new": false,
    "is_coming_soon": false,
    "custom_admin_box_html": "",
    "safety_status": "Verified",
    "slug": "jaiho-rummy-",
    "seo_description": ""
  },
  {
    "version": "1.6",
    "link_configured": true,
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "created_at": "2026-05-26T07:31:59.173Z",
    "file_size": "68",
    "category": "Yono, All App",
    "seo_description": "",
    "slug": "love-rummy",
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "is_coming_soon": false,
    "is_new": false,
    "seo_title": "",
    "id": "l7a60keix",
    "idea_box_msg": "",
    "target_region": "",
    "red_box_msg": "",
    "release_notes": "",
    "features_html": "",
    "name": "Love Rummy",
    "canonical_url": "",
    "custom_admin_box_heading": "",
    "faqs": [],
    "serial_number": 19,
    "developer": "Mak job",
    "is_featured": false,
    "screenshots": [],
    "og_image_url": "",
    "video_url": "",
    "rating": 4.2,
    "yellow_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/cf0b4466-3d5b-4eb5-bc88-afc9a8213ac4/-/preview/190x190/"
  },
  {
    "developer": "AB Arora",
    "is_featured": false,
    "og_image_url": "",
    "screenshots": [],
    "video_url": "",
    "rating": 5,
    "icon_url": "https://13eehe59cj.ucarecd.net/e0898894-5d5b-47ab-a14f-13b4514b3b4f/-/preview/190x190/",
    "yellow_box_msg": "",
    "features_html": "",
    "red_box_msg": "",
    "release_notes": "",
    "canonical_url": "",
    "name": "JOY RUMMY",
    "faqs": [],
    "custom_admin_box_heading": "",
    "serial_number": 20,
    "seo_description": "",
    "slug": "joy-rummy",
    "is_coming_soon": false,
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "seo_title": "",
    "is_new": false,
    "target_region": "",
    "idea_box_msg": "",
    "id": "4paka7kie",
    "version": "1.8",
    "link_configured": false,
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "created_at": "2026-05-26T07:34:35.782Z",
    "file_size": "50",
    "category": "Yono, All App"
  },
  {
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "version": "1.0",
    "link_configured": true,
    "category": "Yono, All App",
    "created_at": "2026-05-26T07:37:07.122Z",
    "file_size": "70",
    "slug": "maha-games",
    "seo_description": "",
    "seo_title": "",
    "is_new": false,
    "target_region": "",
    "idea_box_msg": "",
    "id": "2768ohu2a",
    "is_coming_soon": false,
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "features_html": "",
    "release_notes": "",
    "red_box_msg": "",
    "faqs": [],
    "custom_admin_box_heading": "",
    "serial_number": 21,
    "canonical_url": "",
    "name": "MAHA GAMES",
    "is_featured": false,
    "og_image_url": "",
    "screenshots": [],
    "developer": "AZ ever",
    "yellow_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/2d664adc-3e1f-4317-805c-dea453f52389/-/preview/190x190/",
    "video_url": "",
    "rating": 4
  },
  {
    "custom_admin_box_html": "",
    "safety_status": "Verified",
    "is_coming_soon": false,
    "idea_box_msg": "",
    "id": "us5xuk5bm",
    "target_region": "",
    "is_new": false,
    "seo_title": "",
    "seo_description": "",
    "slug": "rummy-ludo",
    "created_at": "2026-05-26T07:39:44.282Z",
    "file_size": "58",
    "category": "Yono, All App",
    "link_configured": true,
    "version": "5.8",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "rating": 3.9,
    "video_url": "",
    "yellow_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/6aa28ca8-cef1-4d1a-b054-13e242eaef02/-/preview/190x190/",
    "developer": "AZ ever",
    "screenshots": [],
    "og_image_url": "",
    "is_featured": false,
    "name": "Rummy Ludo",
    "canonical_url": "",
    "serial_number": 22,
    "faqs": [],
    "custom_admin_box_heading": "",
    "release_notes": "",
    "red_box_msg": "",
    "features_html": ""
  },
  {
    "category": "Yono, All App",
    "file_size": "45",
    "created_at": "2026-05-26T07:42:24.615Z",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "link_configured": true,
    "version": "2.0.6",
    "target_region": "",
    "id": "69x1lstq7",
    "idea_box_msg": "",
    "seo_title": "",
    "is_new": false,
    "is_coming_soon": false,
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "slug": "rummy-77",
    "seo_description": "",
    "serial_number": 23,
    "faqs": [],
    "custom_admin_box_heading": "",
    "canonical_url": "",
    "name": "Rummy 77",
    "features_html": "",
    "release_notes": "",
    "red_box_msg": "",
    "yellow_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/d17abcfc-c8dc-4c36-8558-e3408002d37e/-/preview/190x190/",
    "rating": 3.9,
    "video_url": "",
    "og_image_url": "",
    "screenshots": [],
    "is_featured": false,
    "developer": "Arcade "
  },
  {
    "file_size": "58",
    "created_at": "2026-05-26T07:44:32.442Z",
    "category": "Yono, All App",
    "version": "1.8",
    "link_configured": false,
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "is_coming_soon": false,
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "seo_title": "",
    "is_new": false,
    "target_region": "",
    "id": "j79n2g3l9",
    "idea_box_msg": "",
    "seo_description": "",
    "slug": "share-slots",
    "canonical_url": "",
    "name": "Share Slots",
    "faqs": [],
    "custom_admin_box_heading": "",
    "serial_number": 24,
    "features_html": "",
    "red_box_msg": "",
    "release_notes": "",
    "video_url": "",
    "rating": 4,
    "yellow_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/2738be7d-f198-4f70-a7d8-c8eb5f452eb0/-/preview/190x190/",
    "developer": "AB Arora",
    "is_featured": false,
    "og_image_url": "",
    "screenshots": []
  },
  {
    "is_coming_soon": false,
    "custom_admin_box_html": "",
    "safety_status": "Verified",
    "target_region": "",
    "idea_box_msg": "",
    "id": "n3w2vjk0b",
    "seo_title": "",
    "is_new": false,
    "seo_description": "",
    "slug": "567-slots",
    "created_at": "2026-05-26T07:51:47.637Z",
    "file_size": "65",
    "category": "Yono, All App",
    "link_configured": true,
    "version": "1.6",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "rating": 3.5,
    "video_url": "",
    "yellow_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/e4314d5e-eb77-46b9-8998-8e0f94970b38/-/preview/72x72/",
    "developer": "Tania JK ",
    "og_image_url": "",
    "screenshots": [],
    "is_featured": false,
    "canonical_url": "",
    "name": "567 SLOTS",
    "serial_number": 26,
    "faqs": [],
    "custom_admin_box_heading": "",
    "features_html": "",
    "red_box_msg": "",
    "release_notes": ""
  },
  {
    "developer": "Admin",
    "og_image_url": "",
    "screenshots": [],
    "is_featured": false,
    "rating": 2.9,
    "video_url": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/a0cedc36-33b0-4e75-a1ea-cd963b3ee0ca/-/preview/190x190/",
    "yellow_box_msg": "",
    "features_html": "",
    "red_box_msg": "",
    "release_notes": "",
    "canonical_url": "",
    "name": "789Jackpots",
    "serial_number": 27,
    "custom_admin_box_heading": "",
    "faqs": [],
    "seo_description": "",
    "slug": "789jackpots",
    "is_coming_soon": false,
    "custom_admin_box_html": "",
    "safety_status": "Verified",
    "target_region": "",
    "id": "owxg4aekg",
    "idea_box_msg": "",
    "seo_title": "",
    "is_new": false,
    "link_configured": true,
    "version": "1.9",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "file_size": "Tanu WD",
    "created_at": "2026-05-26T07:56:30.478Z",
    "category": "Yono, All App"
  },
  {
    "og_image_url": "",
    "screenshots": [],
    "is_featured": false,
    "developer": "Rahul HL",
    "yellow_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/d9226164-7447-425e-ba61-618d72ed28df/-/preview/190x190/",
    "rating": 4,
    "video_url": "",
    "features_html": "",
    "release_notes": "",
    "red_box_msg": "",
    "serial_number": 28,
    "faqs": [],
    "custom_admin_box_heading": "",
    "canonical_url": "",
    "name": "YONO VIP",
    "slug": "yono-vip",
    "seo_description": "",
    "target_region": "",
    "idea_box_msg": "",
    "id": "fw5wsziec",
    "seo_title": "",
    "is_new": false,
    "is_coming_soon": false,
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "link_configured": true,
    "version": "1.8",
    "category": "Yono, All App",
    "file_size": "78",
    "created_at": "2026-05-26T08:00:01.636Z"
  },
  {
    "serial_number": 34,
    "custom_admin_box_heading": "",
    "faqs": [],
    "canonical_url": "",
    "name": "Teen Patti Octro",
    "features_html": "",
    "red_box_msg": "",
    "release_notes": "",
    "icon_url": "https://kk19a1nwwx.ucarecd.net/091fdebe-1562-41c6-99ea-b60665adb5ee/-/preview/512x512/",
    "yellow_box_msg": "",
    "rating": 4.2,
    "video_url": "",
    "og_image_url": "",
    "screenshots": [],
    "is_featured": false,
    "developer": "Unknown ",
    "category": "Card",
    "file_size": "90",
    "created_at": "2026-06-03T10:17:01.058Z",
    "description_html": "<p>A new application.</p>",
    "publish_date": "2026-06-10T12:00:00.000Z",
    "seo_keywords": "",
    "link_configured": true,
    "version": "3",
    "target_region": "",
    "id": "t1ocq5iar",
    "idea_box_msg": "",
    "seo_title": "",
    "is_new": true,
    "is_coming_soon": true,
    "custom_admin_box_html": "",
    "safety_status": "Verified",
    "slug": "teen-patti-octro",
    "seo_description": ""
  },
  {
    "slug": "zynga-poker-texas-holdem-game",
    "seo_description": "",
    "is_new": false,
    "seo_title": "",
    "id": "rrmv44n9n",
    "idea_box_msg": "",
    "target_region": "",
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "is_coming_soon": true,
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "version": "1.0",
    "link_configured": true,
    "category": "Card",
    "file_size": "Unknown",
    "created_at": "2026-06-03T10:30:01.393Z",
    "is_featured": false,
    "screenshots": [],
    "og_image_url": "",
    "developer": "Admin",
    "yellow_box_msg": "",
    "icon_url": "https://kk19a1nwwx.ucarecd.net/5b72cf8f-4959-426e-9e1d-8e2150529efb/-/preview/240x240/",
    "video_url": "",
    "rating": 5,
    "red_box_msg": "",
    "release_notes": "",
    "features_html": "",
    "faqs": [],
    "custom_admin_box_heading": "",
    "serial_number": 29,
    "name": "Zynga Poker- Texas Holdem Game",
    "canonical_url": ""
  },
  {
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "version": "1.0",
    "link_configured": true,
    "category": "Card",
    "file_size": "Unknown",
    "created_at": "2026-06-07T10:14:11.138Z",
    "slug": "uno-",
    "seo_description": "",
    "seo_title": "",
    "is_new": true,
    "target_region": "",
    "idea_box_msg": null,
    "id": "wf59smk6l",
    "is_coming_soon": true,
    "custom_admin_box_html": null,
    "safety_status": "Verified",
    "features_html": null,
    "release_notes": "",
    "red_box_msg": null,
    "faqs": [],
    "custom_admin_box_heading": null,
    "serial_number": 30,
    "canonical_url": "",
    "name": "UNO! ",
    "is_featured": false,
    "og_image_url": "",
    "screenshots": [],
    "developer": "Admin",
    "yellow_box_msg": null,
    "icon_url": "https://1ewg1yyass.ucarecd.net/c0172402-c854-4016-876e-6b7769547c8f/-/preview/238x211/",
    "rating": 5
  },
  {
    "red_box_msg": "",
    "release_notes": "",
    "serial_number": 31,
    "custom_admin_box_heading": "",
    "faqs": [],
    "name": "Rummy GOLD - With Fast Rummy",
    "canonical_url": "",
    "screenshots": [],
    "og_image_url": "",
    "is_featured": false,
    "developer": "Admin",
    "icon_url": "https://1ewg1yyass.ucarecd.net/33e0d4e8-6e41-4791-9e41-8d915a12e504/-/preview/447x447/",
    "yellow_box_msg": "",
    "rating": 5,
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "link_configured": true,
    "version": "1.0",
    "category": "Card",
    "file_size": "Unknown",
    "created_at": "2026-06-07T10:16:45.949Z",
    "slug": "rummy-gold-with-fast-rummy",
    "seo_description": "",
    "id": "8epj9jjpu",
    "idea_box_msg": "",
    "target_region": "",
    "is_new": false,
    "seo_title": "",
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "is_coming_soon": true
  },
  {
    "developer": "Admin",
    "screenshots": [],
    "og_image_url": "",
    "is_featured": false,
    "rating": 5,
    "icon_url": "https://1ewg1yyass.ucarecd.net/2a4b59ef-16a3-4b14-bad3-1c3796af3492/-/preview/447x447/",
    "yellow_box_msg": null,
    "red_box_msg": null,
    "release_notes": "",
    "features_html": null,
    "name": "Indian Rummy 3 Patti Card Game",
    "canonical_url": "",
    "serial_number": 32,
    "custom_admin_box_heading": null,
    "faqs": [],
    "seo_description": "",
    "slug": "indian-rummy-3-patti-card-game",
    "safety_status": "Verified",
    "custom_admin_box_html": null,
    "is_coming_soon": true,
    "idea_box_msg": null,
    "id": "8jt0hokyo",
    "target_region": "",
    "is_new": true,
    "seo_title": "",
    "link_configured": true,
    "version": "1.0",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "created_at": "2026-06-07T10:19:11.616Z",
    "file_size": "Unknown",
    "category": "Card"
  },
  {
    "serial_number": 33,
    "custom_admin_box_heading": "",
    "faqs": [],
    "name": "Lucky Spin Slots",
    "canonical_url": "",
    "release_notes": "",
    "red_box_msg": "",
    "features_html": "",
    "yellow_box_msg": "",
    "icon_url": "https://1ewg1yyass.ucarecd.net/0f918f11-b247-4b5a-9d26-d510dddffbfe/-/preview/447x447/",
    "rating": 5,
    "screenshots": [],
    "og_image_url": "https://1ewg1yyass.ucarecd.net/0f918f11-b247-4b5a-9d26-d510dddffbfe/-/preview/447x447/",
    "is_featured": false,
    "developer": "Admin",
    "category": "Slots",
    "file_size": "Unknown",
    "created_at": "2026-06-07T13:13:11.211Z",
    "description_html": "<p>A new application.</p>",
    "publish_date": "2026-07-08T13:08:00.000Z",
    "seo_keywords": "",
    "link_configured": true,
    "version": "1.0",
    "idea_box_msg": "",
    "id": "01x9h7nfb",
    "target_region": "",
    "is_new": false,
    "seo_title": "",
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "is_coming_soon": true,
    "slug": "lucky-spin-slots",
    "seo_description": ""
  },
  {
    "og_image_url": "",
    "screenshots": [],
    "is_featured": false,
    "developer": "AB Arora",
    "icon_url": "https://1ewg1yyass.ucarecd.net/9d9339e0-77d4-418b-86f8-0a0e074c1d4e/-/preview/190x190/",
    "yellow_box_msg": "",
    "rating": 4.5,
    "video_url": "",
    "features_html": "",
    "red_box_msg": "",
    "release_notes": "",
    "serial_number": 28,
    "custom_admin_box_heading": "",
    "faqs": [],
    "canonical_url": "",
    "name": "IND Club",
    "slug": "ind-club",
    "seo_description": "",
    "target_region": "",
    "id": "3cflt97b5",
    "idea_box_msg": "",
    "seo_title": "",
    "is_new": false,
    "is_coming_soon": true,
    "safety_status": "Verified",
    "custom_admin_box_html": "",
    "publish_date": "2026-06-12T15:30:00.000Z",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "link_configured": true,
    "version": "1.0",
    "category": "Yono",
    "file_size": "76",
    "created_at": "2026-06-12T12:39:30.407Z"
  }
];

export const saveMockApps = (apps: AppConfig[]) => {
  try {
    localStorage.setItem('rummystore_apps', JSON.stringify(apps));
  } catch (e) {
    console.warn('saveMockApps storage failed:', e);
  }
  mockApps.splice(0, mockApps.length, ...apps);
};

export const mockSettings: GlobalSettings = {
  "about_content": "<!-- SA",
  "seo_keywords": "M",
  "trending_searches": [
    "RummyApp Online",
    "rummyapp.online",
    "rummyapp",
    "rummy app online review",
    "official rummy app online",
    "go rummy",
    "rummy store application reviews",
    "online gaming facts 2026",
    "gaming blogs india",
    "safe platform gaming",
    "top tier gaming experience",
    "digital entertainment portal",
    "guest play card games",
    "anonymous gaming portal",
    "no login card games",
    "free practice gaming events",
    "Rummy 91 review",
    "Rummy 91 casual app",
    "Rummy 91 game interface",
    "Rummy 91 virtual bonus",
    "play Rummy 91 online",
    "Gogo Rummy app",
    "Gogo Rummy game",
    "Gogo Rummy online",
    "Gogo Rummy review",
    "Gogo Rummy features",
    "Gogo Rummy interface",
    "Gogo Rummy guest mode",
    "Club INR app",
    "Club INR game",
    "Club INR online",
    "Club INR play",
    "Club INR review",
    "Club INR features",
    "Club INR guest mode",
    "ABC Rummy app",
    "ABC Rummy game",
    "ABC Rummy online",
    "ABC Rummy review",
    "ABC Rummy features",
    "ABC Rummy guest mode",
    "777 Rummy app",
    "777 Rummy online",
    "777 Rummy play",
    "777 Rummy review",
    "777 Rummy features",
    "777 Rummy guest mode",
    "Ever 777 app",
    "Ever 777 game",
    "Ever 777 online",
    "Ever 777 play",
    "Ever 777 review",
    "Ever 777 features",
    "Game Rummy app",
    "Game Rummy game",
    "Game Rummy online",
    "Game Rummy review",
    "Game Rummy features",
    "Hi Rummy app",
    "Hi Rummy game",
    "Hi Rummy online",
    "Hi Rummy play",
    "Hi Rummy review",
    "Hi Rummy features",
    "INR Rummy app",
    "INR Rummy game",
    "INR Rummy online",
    "INR Rummy play",
    "INR Rummy review",
    "INR Rummy features",
    "Jaiho Rummy app",
    "Jaiho Rummy game",
    "Jaiho Rummy online",
    "Jaiho Rummy play",
    "Jaiho Rummy review",
    "Love Rummy app",
    "Love Rummy game",
    "Love Rummy online",
    "Love Rummy play",
    "Love Rummy review",
    "Joy Rummy app",
    "Joy Rummy game",
    "Joy Rummy online",
    "Joy Rummy play",
    "Joy Rummy review",
    "Maha Games app",
    "Maha Games game",
    "Maha Games online",
    "Maha Games play",
    "Maha Games review",
    "Rummy Lodo app",
    "Rummy Lodo game",
    "Rummy Lodo online",
    "Rummy Lodo play",
    "Rummy Lodo review",
    "Rummy 77 app",
    "Rummy 77 game",
    "Rummy 77 online",
    "Rummy 77 play",
    "Rummy 77 review",
    "Share Slots app",
    "Share Slots game",
    "Share Slots online",
    "Share Slots play",
    "Share Slots review",
    "567 Slots app",
    "567 Slots game",
    "567 Slots online",
    "567 Slots play",
    "567 Slots review",
    "789 Jackpots app",
    "789 Jackpots game",
    "789 Jackpots online",
    "789 Jackpots play",
    "789 Jackpots review",
    "Yono VIP app",
    "Yono VIP game",
    "Yono VIP online",
    "Yono VIP play",
    "Yono VIP review",
    "yono games alternative",
    "indian rummy variations",
    "13 card rummy strategy",
    "pure sequence logic",
    "pure sequence guide",
    "joker card casual rules",
    "points rummy logic rules",
    "pool rummy strategy",
    "deals rummy tips",
    "drop point logic rules",
    "advanced rummy tactics",
    "beginner rummy tutorial",
    "real skill rummy simulation",
    "virtual skill rummy portal",
    "smooth card sorting",
    "lag free rummy gaming",
    "digital rummy table",
    "virtual gaming wallet",
    "premium strategy rummy platform",
    "drop rules in rummy",
    "skill based gaming portal",
    "lucky casual slot games"
  ],
  "hero_title_style": "mono",
  "quick_links": [],
  "important_notice": "<div ",
  "terms_content": "<!-- ",
  "privacy_content": "<!-- ",
  "contact_content": "<p>Have questions or feedback? We'd love to hear from you. Our team typically responds within 24-48 hours.</p>",
  "ethics_discrimination_text": "<div ",
  "ticker_text": "LIVE: Unbiased words. Uncompromised truth. RummyApp Online  delivers pure transparency through independent reviews. ✒️",
  "portal_heading": "IMPORTANT NOTICE ",
  "secure_index_subtitle": "The Ultimate Registry for Strategic Card Simulation, Arcade Logic, and Premium Virtual Gameplay Guides",
  "logo_url": "https://y4q7avawns.ucarecd.net/b391a2fa-42f7-4b3a-a0d5-605cb22aead4/-/preview/1000x1000/",
  "hero_title_subtitle": "Step into the world of Rummy - compete, challenge friends, and rise to the top on RummyApp Online!",
  "hero_title_color": "neon-sky",
  "disclaimer_text": "<div ",
  "ethics_heading": "ETHNICS",
  "disclaimer_heading": "DISCLAIMER ",
  "helpline_telegram": "https://t.me/+d_B",
  "meta_description": "Ok ",
  "banners": [
    {
      "image": "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
      "subtitle": "Subtitle text",
      "link": "/",
      "id": "mgg408of3",
      "title": "New Banner"
    }
  ],
  "support_email": "support@rummyapp.online",
  "website_faqs": [],
  "hero_title_text": "RummyApp Online ",
  "site_title": "RummyDex ",
  "hero_title_animation": "slide-up",
  "responsibility_content": "<!-- ",
  "social_links": {
    "facebook": "",
    "instagram": "",
    "youtube": "",
    "twitter": "",
    "linkedin": ""
  },
  "hero_title_visible": true,
  "animations_enabled": true,
  "secure_index_title": "RummyDex ",
  "last_updated": "2026-07-19T02:06:04.833Z",
  "important_notice_heading": "VERY IMPORTANT NOTICE ",
  "favicon_url": "https://y4q7avawns.ucarecd.net/b391a2fa-42f7-4b3a-a0d5-605cb22aead4/-/preview/1000x1000/",
  "categories": [
    "Yono",
    "Card",
    "Slots"
  ],
  "helpline_whatsapp": "+918653034735"
};

export const saveMockSettings = (settings: GlobalSettings) => {
  try {
    localStorage.setItem('rummystore_settings', JSON.stringify(settings));
  } catch (e) {
    console.warn('saveMockSettings storage failed:', e);
  }
  Object.assign(mockSettings, settings);
};

export const mockNews: NewsItem[] = [
  {
    "slug": "new-news",
    "ceo_name": "CEO Nameug",
    "og_image_url": "",
    "seo_description": "News SEO Meta Description",
    "read_time": "2 min",
    "ceo_description": "CEO Description",
    "logo_url": "",
    "target_region": "Global",
    "id": "876hijgbk",
    "seo_title": "News SEO Titlegdgd",
    "link": "Yirkgd",
    "description_html": "<p>News HTML...</p>",
    "tags": [],
    "seo_keywords": "",
    "content": "Detailed markdown content hehfkgsjtstkdjtsnfsjfzjfsjfsfjsre...",
    "date": "2026-07-20T14:07:40.082Z",
    "category": "Ufuf",
    "title": "Suhan",
    "canonical_url": "",
    "description": "News description...ydyldkgsitsjfahdau",
    "author": "Admin"
  }
];

export const saveMockNews = (newsList: NewsItem[]) => {
  try {
    localStorage.setItem('rummystore_news', JSON.stringify(newsList));
  } catch (e) {
    console.warn('saveMockNews storage failed:', e);
  }
  mockNews.splice(0, mockNews.length, ...newsList);
};

export const mockBlogs: BlogPost[] = [];

export const saveMockBlogs = (blogs: BlogPost[]) => {
  try {
    localStorage.setItem('rummystore_blogs', JSON.stringify(blogs));
  } catch (e) {
    console.warn('saveMockBlogs storage failed:', e);
  }
  mockBlogs.splice(0, mockBlogs.length, ...blogs);
};

export const mockVideos: VideoItem[] = [
  {
    "description": "Looking for the best UI SMOOTH experience rummy ",
    "youtube_url": "https://youtu.be/0uPeAuXIRdQ?si=aP9WFCyYCHKW2z5F",
    "created_at": "2026-05-22T12:22:35.244Z",
    "seo_description": "",
    "seo_title": "Rummy ",
    "title": "RummyApp Online ",
    "id": "1",
    "slug": ""
  },
  {
    "created_at": "2026-05-29T14:26:28.226Z",
    "description": "",
    "id": "73jeeqtsr",
    "title": "",
    "seo_title": "",
    "seo_description": "",
    "youtube_url": "",
    "slug": "",
    "seo_keywords": ""
  }
];

export const saveMockVideos = (videos: VideoItem[]) => {
  try {
    localStorage.setItem('rummystore_videos', JSON.stringify(videos));
  } catch (e) {
    console.warn('saveMockVideos storage failed:', e);
  }
  mockVideos.splice(0, mockVideos.length, ...videos);
};
