// No secureStorage import to avoid Vercel build errors when secureStorage is stripped

export interface Banner {
  id: string;
  title: string;
  subtitle: string;
  image: string;
  link: string;
}

export interface GlobalSettings {
  site_title: string;
  meta_description: string;
  logo_url: string;
  favicon_url: string;
  helpline_whatsapp: string;
  helpline_telegram: string;
  support_email: string;
  disclaimer_text: string;
  disclaimer_heading?: string;
  ethics_discrimination_text: string;
  ethics_heading?: string;
  portal_heading?: string;
  important_notice_heading?: string;
  ticker_text: string;
  animations_enabled: boolean;
  seo_keywords?: string;
  about_content?: string;
  contact_content?: string;
  privacy_content?: string;
  terms_content?: string;
  responsibility_content?: string;
  important_notice?: string;
  categories: string[];
  banners: Banner[];
  last_updated?: string;
  secure_index_title?: string;
  secure_index_subtitle?: string;
  trending_searches?: string[];
  hero_title_text?: string;
  hero_title_color?: string;
  hero_title_style?: string;
  hero_title_animation?: string;
  hero_title_subtitle?: string;
  hero_title_visible?: boolean;
  ga_tracking_id?: string;
  quick_links?: Array<{ title: string; subtitle?: string; icon?: string; color?: string; url: string }>;
  social_links?: { facebook?: string; instagram?: string; twitter?: string; linkedin?: string; youtube?: string; };
  website_faqs?: Array<{ question: string; answer: string }>;
  developers?: Array<{ name: string; role: string; bio?: string; image_url?: string; github?: string; twitter?: string; avatar_url?: string; social?: any }>;
}

export interface NewsItem {
  id: string;
  slug: string;
  title: string;
  logo_url: string;
  description: string;
  ceo_name: string;
  ceo_description: string;
  seo_title: string;
  seo_description: string;
  seo_keywords?: string;
  category?: string;
  og_image_url?: string;
  canonical_url?: string;
  target_region?: string;
  content: string;
  published_at?: string;
  link: string;
  read_time?: string;
  author?: string;
  description_html?: string;
  date?: string;
  tags?: string[];
}

export interface AppConfig {
  id: string;
  name: string;
  slug: string;
  seo_title?: string;
  seo_description?: string;
  seo_keywords?: string;
  og_image_url?: string;
  canonical_url?: string;
  target_region?: string;
  category: string;
  is_coming_soon?: boolean;
  publish_date?: string;
  version: string;
  file_size: string;
  developer: string;
  icon_url: string;
  screenshots: string[];
  description_html: string;
  red_box_msg: string;
  yellow_box_msg: string;
  idea_box_msg: string;
  safety_status: 'Verified' | 'Caution' | 'Unsafe';
  serial_number: number;
  is_featured: boolean;
  is_new: boolean;
  release_notes: string;
  rating: number;
  created_at: string;
  custom_admin_box_html?: string;
  custom_admin_box_heading?: string;
  features_html?: string;
  faqs?: {question: string; answer: string}[];
  link_configured?: boolean;
  
  video_url?: string;
  is_top_chart?: boolean;
  top_chart_category?: string;
  more_information_url?: string;
}

export interface Review {
  id: string;
  app_id: string;
  username: string;
  rating: number;
  comment: string;
  is_approved: boolean;
}

export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  content: string;
  author: string;
  cover_url: string;
  published_at: string;
  related_app_slug?: string;
  related_app_name?: string;
  seo_title?: string;
  seo_description?: string;
  seo_keywords?: string;
  canonical_url?: string;
  target_region?: string;
  description?: string;
  description_html?: string;
  date?: string;
  thumbnail_url?: string;
  publish_date?: string;
  read_time?: string;
  tags?: string[];
  created_at?: string;
}

export interface NewsUpdate {
  id: string;
  title: string;
  content_html: string;
  category: string;
  published_at: string;
}

export interface VideoItem {
  id: string;
  slug: string;
  title: string;
  description: string;
  youtube_url: string;
  seo_title: string;
  seo_description: string;
  seo_keywords?: string;
  created_at: string;
}

export const mockApps: AppConfig[] = [
  {
    "video_url": "",
    "target_region": "",
    "idea_box_msg": "",
    "custom_admin_box_html": "",
    "icon_url": "https://res.cloudinary.com/dq34n0ncz/image/upload/f_auto,q_auto/1000119573_wzwse4",
    "features_html": "",
    "version": "2.0.6",
    "is_featured": false,
    "yellow_box_msg": "",
    "screenshots": [],
    "faqs": [],
    "red_box_msg": "",
    "is_coming_soon": false,
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "is_top_chart": true,
    "name": "SPIN CRUSH ",
    "developer": "Bingo ",
    "category": "Yono, All App",
    "rating": 5,
    "safety_status": "Verified",
    "serial_number": 2,
    "file_size": "45",
    "is_new": true,
    "release_notes": "",
    "description_html": "<p>A new application.</p>",
    "slug": "spin-crush-",
    "id": "q82dbbwh4",
    "seo_description": "",
    "canonical_url": "",
    "created_at": "2026-05-19T12:43:59.040Z",
    "is_hot": false,
    "seo_keywords": "",
    "link_configured": true,
    "seo_title": ""
  },
  {
    "red_box_msg": "",
    "faqs": [],
    "screenshots": [],
    "yellow_box_msg": "",
    "version": "1.20.1",
    "is_featured": false,
    "features_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/67a16d31-6771-4617-b88b-288db51d321d/-/preview/554x554/",
    "custom_admin_box_html": "",
    "idea_box_msg": "",
    "target_region": "",
    "video_url": "",
    "link_configured": false,
    "seo_title": "",
    "seo_keywords": "",
    "created_at": "2026-05-19T19:04:26.373Z",
    "id": "31og4l26i",
    "slug": "yono-arcade",
    "description_html": "<p>A new application.</p>",
    "seo_description": "",
    "canonical_url": "",
    "release_notes": "",
    "is_new": false,
    "serial_number": 3,
    "file_size": "56",
    "category": "Yono, All App",
    "rating": 3.4,
    "safety_status": "Verified",
    "developer": "Arcade ",
    "name": "YONO ARCADE",
    "og_image_url": "",
    "custom_admin_box_heading": "",
    "is_coming_soon": false
  },
  {
    "safety_status": "Verified",
    "rating": 4.8,
    "category": "Yono, All App",
    "developer": "Jaiho",
    "is_new": true,
    "serial_number": 3,
    "file_size": "56",
    "og_image_url": "",
    "custom_admin_box_heading": "",
    "is_coming_soon": false,
    "name": "JAIHO 91",
    "seo_keywords": "",
    "link_configured": true,
    "seo_title": "",
    "release_notes": "",
    "created_at": "2026-05-19T19:23:07.133Z",
    "canonical_url": "",
    "seo_description": "",
    "slug": "jaiho-91",
    "id": "s5u553ymi",
    "description_html": "<p>A new application.</p>",
    "idea_box_msg": "",
    "icon_url": "https://res.cloudinary.com/dyigysy26/image/upload/f_auto,q_auto/1000119609_fkc9fm",
    "custom_admin_box_html": "",
    "video_url": "",
    "target_region": "",
    "screenshots": [],
    "yellow_box_msg": "",
    "red_box_msg": "",
    "faqs": [],
    "features_html": "",
    "is_featured": false,
    "version": "1.20.1"
  },
  {
    "link_configured": true,
    "seo_title": "",
    "seo_keywords": "",
    "slug": "bingo-101",
    "id": "awus3qajs",
    "description_html": "<p>A new application.</p>",
    "seo_description": "",
    "canonical_url": "",
    "created_at": "2026-05-20T03:09:33.880Z",
    "release_notes": "",
    "serial_number": 5,
    "file_size": "71",
    "is_new": false,
    "developer": "Bingo",
    "rating": 3.6,
    "category": "Yono, All App",
    "safety_status": "Verified",
    "name": "BINGO 101",
    "is_coming_soon": false,
    "og_image_url": "",
    "custom_admin_box_heading": "",
    "faqs": [],
    "red_box_msg": "",
    "yellow_box_msg": "",
    "screenshots": [],
    "version": "2.5V",
    "is_featured": false,
    "features_html": "",
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/d3f6486a-b216-4582-b15d-0c735ff6b08f/-/preview/554x554/",
    "idea_box_msg": "",
    "target_region": "",
    "video_url": ""
  },
  {
    "features_html": "",
    "version": "8.3.06.",
    "is_featured": false,
    "screenshots": [],
    "yellow_box_msg": "",
    "faqs": [],
    "red_box_msg": "",
    "video_url": "",
    "target_region": "",
    "idea_box_msg": "",
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/97512d34-f561-4ede-8517-2112440079eb/-/preview/554x554/",
    "release_notes": "",
    "slug": "ok-rummy",
    "id": "0uiuuhdrj",
    "description_html": "<p>A new application.</p>",
    "canonical_url": "",
    "seo_description": "",
    "created_at": "2026-05-20T03:50:33.674Z",
    "seo_keywords": "",
    "seo_title": "",
    "link_configured": true,
    "is_coming_soon": false,
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "name": "OK RUMMY",
    "developer": "Bingo ",
    "category": "Yono, All App",
    "rating": 3,
    "safety_status": "Verified",
    "file_size": "67",
    "serial_number": 6,
    "is_new": false
  },
  {
    "yellow_box_msg": "",
    "screenshots": [],
    "red_box_msg": "",
    "faqs": [],
    "features_html": "",
    "version": "4.3",
    "is_featured": false,
    "idea_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/2dfe5d55-7896-4f96-8f2b-132190e44f6f/-/preview/540x540/",
    "custom_admin_box_html": "",
    "video_url": "",
    "target_region": "",
    "seo_keywords": "",
    "seo_title": "",
    "link_configured": true,
    "release_notes": "",
    "created_at": "2026-05-20T03:53:24.482Z",
    "description_html": "<p>A new application.</p>",
    "slug": "jaiho-slots",
    "id": "4yt0f4yd0",
    "canonical_url": "",
    "seo_description": "",
    "rating": 4.9,
    "category": "Yono, All App",
    "safety_status": "Verified",
    "developer": "Jaiho",
    "is_new": false,
    "file_size": "70",
    "serial_number": 7,
    "og_image_url": "",
    "custom_admin_box_heading": "",
    "is_coming_soon": false,
    "name": "JAIHO SLOTS"
  },
  {
    "name": "BOSS RUMMY",
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "is_coming_soon": false,
    "is_new": false,
    "serial_number": 8,
    "file_size": "54",
    "safety_status": "Verified",
    "category": "Yono, All App",
    "rating": 4.1,
    "developer": "Arcade ",
    "created_at": "2026-05-20T03:56:42.075Z",
    "canonical_url": "",
    "seo_description": "",
    "description_html": "<p>A new application.</p>",
    "slug": "boss-rummy",
    "id": "9r044fyi0",
    "release_notes": "",
    "seo_title": "",
    "link_configured": true,
    "seo_keywords": "",
    "target_region": "",
    "video_url": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/b5e9d896-71e8-49d6-b091-a971871161e0/-/preview/1000x1000/",
    "custom_admin_box_html": "",
    "idea_box_msg": "",
    "is_featured": false,
    "version": "2.5V",
    "features_html": "",
    "faqs": [],
    "red_box_msg": "",
    "yellow_box_msg": "",
    "screenshots": []
  },
  {
    "faqs": [],
    "red_box_msg": "",
    "screenshots": [],
    "yellow_box_msg": "",
    "is_featured": false,
    "version": "2.0.6",
    "features_html": "",
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/393c07ea-4f5e-43a9-ab0c-e12dfe7d755a/-/preview/474x474/",
    "idea_box_msg": "",
    "target_region": "",
    "video_url": "",
    "link_configured": true,
    "seo_title": "",
    "seo_keywords": "",
    "canonical_url": "",
    "seo_description": "",
    "slug": "rummy-91",
    "id": "5b7fj0cq7",
    "description_html": "<p>A new application.</p>",
    "created_at": "2026-05-20T04:01:04.611Z",
    "release_notes": "",
    "serial_number": 9,
    "file_size": "79",
    "is_new": false,
    "developer": "Addi",
    "safety_status": "Verified",
    "rating": 4.9,
    "category": "All App",
    "name": "RUMMY 91",
    "is_coming_soon": false,
    "og_image_url": "",
    "custom_admin_box_heading": ""
  },
  {
    "seo_title": "",
    "link_configured": true,
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "slug": "gogo-rummy-",
    "id": "ieam3hkbq",
    "canonical_url": "",
    "seo_description": "",
    "created_at": "2026-05-20T06:58:27.643Z",
    "release_notes": "",
    "serial_number": 10,
    "file_size": "65",
    "is_new": false,
    "developer": "Sk varba",
    "category": "Yono, All App",
    "rating": 3.9,
    "safety_status": "Verified",
    "name": "GOGO RUMMY ",
    "is_coming_soon": false,
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "red_box_msg": "",
    "faqs": [],
    "yellow_box_msg": "",
    "screenshots": [],
    "version": "5.0",
    "is_featured": false,
    "features_html": "",
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/0d710f11-2c9d-4312-89de-be65ce21a4fe/-/preview/750x750/",
    "idea_box_msg": "",
    "target_region": "",
    "video_url": ""
  },
  {
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/3059d25d-1497-4cff-aead-68758187fe0b/-/preview/554x554/",
    "idea_box_msg": "",
    "target_region": "",
    "video_url": "",
    "faqs": [],
    "red_box_msg": "",
    "screenshots": [],
    "yellow_box_msg": "",
    "is_featured": false,
    "version": "1.8",
    "features_html": "",
    "file_size": "75",
    "serial_number": 11,
    "is_new": false,
    "developer": "S.A vejay",
    "safety_status": "Verified",
    "category": "Yono, All App",
    "rating": 4.6,
    "name": "CLUB INR",
    "is_coming_soon": false,
    "og_image_url": "",
    "custom_admin_box_heading": "",
    "link_configured": true,
    "seo_title": "",
    "seo_keywords": "",
    "canonical_url": "",
    "seo_description": "",
    "id": "5j5b7qbrw",
    "description_html": "<p>A new application.</p>",
    "slug": "club-inr",
    "created_at": "2026-05-20T08:02:40.971Z",
    "release_notes": ""
  },
  {
    "developer": "Addi",
    "safety_status": "Verified",
    "category": "Yono, All App",
    "rating": 3.9,
    "serial_number": 12,
    "file_size": "61",
    "is_new": false,
    "is_coming_soon": false,
    "og_image_url": "",
    "custom_admin_box_heading": "",
    "name": "ABC Rummy ",
    "seo_keywords": "",
    "seo_title": "",
    "link_configured": true,
    "release_notes": "",
    "canonical_url": "",
    "seo_description": "",
    "id": "f4ktp4dfi",
    "description_html": "<p>A new application.</p>",
    "slug": "abc-rummy-",
    "created_at": "2026-05-26T07:04:36.330Z",
    "idea_box_msg": "",
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/f7108631-b74a-49e5-8abf-37cec6950f7c/-/preview/512x512/",
    "video_url": "",
    "target_region": "",
    "screenshots": [],
    "yellow_box_msg": "",
    "faqs": [],
    "red_box_msg": "",
    "features_html": "",
    "is_featured": false,
    "version": "1.8"
  },
  {
    "link_configured": true,
    "seo_title": "",
    "seo_keywords": "",
    "description_html": "<p>A new application.</p>",
    "slug": "777-rummy",
    "id": "4w1yxs6mm",
    "seo_description": "",
    "canonical_url": "",
    "created_at": "2026-05-26T07:09:01.068Z",
    "release_notes": "",
    "file_size": "54",
    "serial_number": 13,
    "is_new": false,
    "developer": "AB Arora",
    "category": "Yono, All App",
    "rating": 5,
    "safety_status": "Verified",
    "name": "777.Rummy",
    "is_coming_soon": false,
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "faqs": [],
    "red_box_msg": "",
    "yellow_box_msg": "",
    "screenshots": [],
    "version": "1.6",
    "is_featured": false,
    "features_html": "",
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/fb951184-b849-4ff0-8882-a4d826508fb7/-/preview/190x190/",
    "idea_box_msg": "",
    "target_region": "",
    "video_url": ""
  },
  {
    "yellow_box_msg": "",
    "screenshots": [],
    "red_box_msg": "",
    "faqs": [],
    "features_html": "",
    "is_featured": false,
    "version": "1.8",
    "idea_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/74347710-3cb2-468c-98eb-5666a0af487c/-/preview/190x190/",
    "custom_admin_box_html": "",
    "video_url": "",
    "target_region": "",
    "seo_keywords": "",
    "link_configured": true,
    "seo_title": "",
    "release_notes": "",
    "created_at": "2026-05-26T07:12:55.821Z",
    "seo_description": "",
    "canonical_url": "",
    "description_html": "<p>A new application.</p>",
    "slug": "ever-777",
    "id": "w1sttlwv7",
    "safety_status": "Verified",
    "category": "Yono, All App",
    "rating": 4,
    "developer": "AZ ever",
    "is_new": false,
    "serial_number": 14,
    "file_size": "59",
    "og_image_url": "",
    "custom_admin_box_heading": "",
    "is_coming_soon": false,
    "name": "EVER 777"
  },
  {
    "canonical_url": "",
    "seo_description": "",
    "slug": "game-rummy",
    "id": "dp2lcn2ae",
    "description_html": "<p>A new application.</p>",
    "created_at": "2026-05-26T07:16:08.600Z",
    "release_notes": "",
    "link_configured": true,
    "seo_title": "",
    "seo_keywords": "",
    "name": "Game Rummy",
    "is_coming_soon": false,
    "og_image_url": "",
    "custom_admin_box_heading": "",
    "file_size": "75",
    "serial_number": 15,
    "is_new": false,
    "developer": "Raj dav",
    "safety_status": "Verified",
    "category": "Yono, All App",
    "rating": 4,
    "is_featured": false,
    "version": "2.0",
    "features_html": "",
    "faqs": [],
    "red_box_msg": "",
    "yellow_box_msg": "",
    "screenshots": [],
    "target_region": "",
    "video_url": "",
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/4b2bd57d-9855-40a8-b452-34edee84ed09/-/preview/190x190/",
    "idea_box_msg": ""
  },
  {
    "is_new": false,
    "serial_number": 16,
    "file_size": "54",
    "safety_status": "Verified",
    "category": "Yono, All App",
    "rating": 4.1,
    "developer": "Addi",
    "name": "Hi Rummy ",
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "is_coming_soon": false,
    "seo_title": "",
    "link_configured": true,
    "seo_keywords": "",
    "created_at": "2026-05-26T07:18:29.456Z",
    "seo_description": "",
    "canonical_url": "",
    "description_html": "<p>A new application.</p>",
    "slug": "hi-rummy-",
    "id": "4lgypb90h",
    "release_notes": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/c01e9676-e748-4342-9ac7-e972030981fc/-/preview/190x190/",
    "custom_admin_box_html": "",
    "idea_box_msg": "",
    "target_region": "",
    "video_url": "",
    "faqs": [],
    "red_box_msg": "",
    "screenshots": [],
    "yellow_box_msg": "",
    "is_featured": false,
    "version": "1.9",
    "features_html": ""
  },
  {
    "screenshots": [],
    "yellow_box_msg": "",
    "red_box_msg": "",
    "faqs": [],
    "features_html": "",
    "version": "3.0",
    "is_featured": false,
    "idea_box_msg": "",
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/2a718650-0602-495f-9ca4-b13c86e58c02/-/preview/190x190/",
    "video_url": "",
    "target_region": "",
    "is_hot": false,
    "seo_keywords": "",
    "seo_title": "",
    "link_configured": true,
    "release_notes": "",
    "id": "2f90a87hv",
    "slug": "inr-rummy",
    "description_html": "<p>A new application.</p>",
    "canonical_url": "",
    "seo_description": "",
    "created_at": "2026-05-26T07:21:55.085Z",
    "developer": "Arcade ",
    "category": "Yono, All App",
    "rating": 5,
    "safety_status": "Verified",
    "serial_number": 17,
    "file_size": "79",
    "is_new": false,
    "is_coming_soon": false,
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "name": "INR Rummy"
  },
  {
    "seo_keywords": "",
    "seo_title": "",
    "link_configured": true,
    "release_notes": "",
    "seo_description": "",
    "canonical_url": "",
    "description_html": "<p>A new application.</p>",
    "id": "9a05609sb",
    "slug": "jaiho-rummy-",
    "created_at": "2026-05-26T07:26:42.606Z",
    "developer": "PW sahar",
    "safety_status": "Verified",
    "category": "Yono, All App",
    "rating": 3.9,
    "file_size": "2.4",
    "serial_number": 18,
    "is_new": false,
    "is_coming_soon": false,
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "name": "JAIHO RUMMY ",
    "screenshots": [],
    "yellow_box_msg": "",
    "faqs": [],
    "red_box_msg": "",
    "features_html": "",
    "is_featured": false,
    "version": "2.1",
    "idea_box_msg": "",
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/c693366d-d543-4d76-84ba-3963a3f3c792/-/preview/190x190/",
    "video_url": "",
    "target_region": ""
  },
  {
    "video_url": "",
    "target_region": "",
    "idea_box_msg": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/cf0b4466-3d5b-4eb5-bc88-afc9a8213ac4/-/preview/190x190/",
    "custom_admin_box_html": "",
    "features_html": "",
    "is_featured": false,
    "version": "1.6",
    "screenshots": [],
    "yellow_box_msg": "",
    "red_box_msg": "",
    "faqs": [],
    "og_image_url": "",
    "custom_admin_box_heading": "",
    "is_coming_soon": false,
    "name": "Love Rummy",
    "safety_status": "Verified",
    "category": "Yono, All App",
    "rating": 4.2,
    "developer": "Mak job",
    "is_new": false,
    "file_size": "68",
    "serial_number": 19,
    "release_notes": "",
    "created_at": "2026-05-26T07:31:59.173Z",
    "canonical_url": "",
    "seo_description": "",
    "id": "l7a60keix",
    "slug": "love-rummy",
    "description_html": "<p>A new application.</p>",
    "seo_keywords": "",
    "link_configured": true,
    "seo_title": ""
  },
  {
    "name": "JOY RUMMY",
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "is_coming_soon": false,
    "is_new": false,
    "file_size": "50",
    "serial_number": 20,
    "safety_status": "Verified",
    "rating": 5,
    "category": "Yono, All App",
    "developer": "AB Arora",
    "created_at": "2026-05-26T07:34:35.782Z",
    "canonical_url": "",
    "seo_description": "",
    "description_html": "<p>A new application.</p>",
    "slug": "joy-rummy",
    "id": "4paka7kie",
    "release_notes": "",
    "link_configured": false,
    "seo_title": "",
    "seo_keywords": "",
    "target_region": "",
    "video_url": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/e0898894-5d5b-47ab-a14f-13b4514b3b4f/-/preview/190x190/",
    "custom_admin_box_html": "",
    "idea_box_msg": "",
    "is_featured": false,
    "version": "1.8",
    "features_html": "",
    "red_box_msg": "",
    "faqs": [],
    "yellow_box_msg": "",
    "screenshots": []
  },
  {
    "faqs": [],
    "red_box_msg": "",
    "screenshots": [],
    "yellow_box_msg": "",
    "version": "1.0",
    "is_featured": false,
    "features_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/2d664adc-3e1f-4317-805c-dea453f52389/-/preview/190x190/",
    "custom_admin_box_html": "",
    "idea_box_msg": "",
    "target_region": "",
    "video_url": "",
    "seo_title": "",
    "link_configured": true,
    "seo_keywords": "",
    "created_at": "2026-05-26T07:37:07.122Z",
    "description_html": "<p>A new application.</p>",
    "id": "2768ohu2a",
    "slug": "maha-games",
    "seo_description": "",
    "canonical_url": "",
    "release_notes": "",
    "is_new": false,
    "serial_number": 21,
    "file_size": "70",
    "category": "Yono, All App",
    "rating": 4,
    "safety_status": "Verified",
    "developer": "AZ ever",
    "name": "MAHA GAMES",
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "is_coming_soon": false
  },
  {
    "features_html": "",
    "is_featured": false,
    "version": "5.8",
    "screenshots": [],
    "yellow_box_msg": "",
    "faqs": [],
    "red_box_msg": "",
    "video_url": "",
    "target_region": "",
    "idea_box_msg": "",
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/6aa28ca8-cef1-4d1a-b054-13e242eaef02/-/preview/190x190/",
    "release_notes": "",
    "seo_description": "",
    "canonical_url": "",
    "id": "us5xuk5bm",
    "slug": "rummy-ludo",
    "description_html": "<p>A new application.</p>",
    "created_at": "2026-05-26T07:39:44.282Z",
    "seo_keywords": "",
    "seo_title": "",
    "link_configured": true,
    "is_coming_soon": false,
    "og_image_url": "",
    "custom_admin_box_heading": "",
    "name": "Rummy Ludo",
    "developer": "AZ ever",
    "safety_status": "Verified",
    "rating": 3.9,
    "category": "Yono, All App",
    "file_size": "58",
    "serial_number": 22,
    "is_new": false
  },
  {
    "is_featured": false,
    "version": "2.0.6",
    "features_html": "",
    "red_box_msg": "",
    "faqs": [],
    "screenshots": [],
    "yellow_box_msg": "",
    "target_region": "",
    "video_url": "",
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/d17abcfc-c8dc-4c36-8558-e3408002d37e/-/preview/190x190/",
    "idea_box_msg": "",
    "canonical_url": "",
    "seo_description": "",
    "id": "69x1lstq7",
    "slug": "rummy-77",
    "description_html": "<p>A new application.</p>",
    "created_at": "2026-05-26T07:42:24.615Z",
    "release_notes": "",
    "link_configured": true,
    "seo_title": "",
    "seo_keywords": "",
    "name": "Rummy 77",
    "is_coming_soon": false,
    "og_image_url": "",
    "custom_admin_box_heading": "",
    "serial_number": 23,
    "file_size": "45",
    "is_new": false,
    "developer": "Arcade ",
    "safety_status": "Verified",
    "category": "Yono, All App",
    "rating": 3.9
  },
  {
    "release_notes": "",
    "seo_description": "",
    "canonical_url": "",
    "description_html": "<p>A new application.</p>",
    "slug": "share-slots",
    "id": "j79n2g3l9",
    "created_at": "2026-05-26T07:44:32.442Z",
    "seo_keywords": "",
    "seo_title": "",
    "link_configured": false,
    "is_coming_soon": false,
    "og_image_url": "",
    "custom_admin_box_heading": "",
    "name": "Share Slots",
    "developer": "AB Arora",
    "safety_status": "Verified",
    "rating": 4,
    "category": "Yono, All App",
    "file_size": "58",
    "serial_number": 24,
    "is_new": false,
    "features_html": "",
    "is_featured": false,
    "version": "1.8",
    "yellow_box_msg": "",
    "screenshots": [],
    "faqs": [],
    "red_box_msg": "",
    "video_url": "",
    "target_region": "",
    "idea_box_msg": "",
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/2738be7d-f198-4f70-a7d8-c8eb5f452eb0/-/preview/190x190/"
  },
  {
    "is_featured": false,
    "version": "1.6",
    "features_html": "",
    "red_box_msg": "",
    "faqs": [],
    "yellow_box_msg": "",
    "screenshots": [],
    "target_region": "",
    "video_url": "",
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/e4314d5e-eb77-46b9-8998-8e0f94970b38/-/preview/72x72/",
    "idea_box_msg": "",
    "canonical_url": "",
    "seo_description": "",
    "slug": "567-slots",
    "id": "n3w2vjk0b",
    "description_html": "<p>A new application.</p>",
    "created_at": "2026-05-26T07:51:47.637Z",
    "release_notes": "",
    "link_configured": true,
    "seo_title": "",
    "seo_keywords": "",
    "name": "567 SLOTS",
    "is_coming_soon": false,
    "og_image_url": "",
    "custom_admin_box_heading": "",
    "file_size": "65",
    "serial_number": 26,
    "is_new": false,
    "developer": "Tania JK ",
    "safety_status": "Verified",
    "rating": 3.5,
    "category": "Yono, All App"
  },
  {
    "idea_box_msg": "",
    "custom_admin_box_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/a0cedc36-33b0-4e75-a1ea-cd963b3ee0ca/-/preview/190x190/",
    "video_url": "",
    "target_region": "",
    "screenshots": [],
    "yellow_box_msg": "",
    "red_box_msg": "",
    "faqs": [],
    "features_html": "",
    "is_featured": false,
    "version": "1.9",
    "developer": "Admin",
    "safety_status": "Verified",
    "rating": 2.9,
    "category": "Yono, All App",
    "file_size": "Tanu WD",
    "serial_number": 27,
    "is_new": false,
    "is_coming_soon": false,
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "name": "789Jackpots",
    "seo_keywords": "",
    "seo_title": "",
    "link_configured": true,
    "release_notes": "",
    "canonical_url": "",
    "seo_description": "",
    "description_html": "<p>A new application.</p>",
    "id": "owxg4aekg",
    "slug": "789jackpots",
    "created_at": "2026-05-26T07:56:30.478Z"
  },
  {
    "link_configured": true,
    "seo_title": "",
    "seo_keywords": "",
    "created_at": "2026-05-26T08:00:01.636Z",
    "seo_description": "",
    "canonical_url": "",
    "description_html": "<p>A new application.</p>",
    "slug": "yono-vip",
    "id": "fw5wsziec",
    "release_notes": "",
    "is_new": false,
    "serial_number": 28,
    "file_size": "78",
    "safety_status": "Verified",
    "rating": 4,
    "category": "Yono, All App",
    "developer": "Rahul HL",
    "name": "YONO VIP",
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "is_coming_soon": false,
    "red_box_msg": "",
    "faqs": [],
    "yellow_box_msg": "",
    "screenshots": [],
    "is_featured": false,
    "version": "1.8",
    "features_html": "",
    "icon_url": "https://13eehe59cj.ucarecd.net/d9226164-7447-425e-ba61-618d72ed28df/-/preview/190x190/",
    "custom_admin_box_html": "",
    "idea_box_msg": "",
    "target_region": "",
    "video_url": ""
  },
  {
    "created_at": "2026-06-03T10:17:01.058Z",
    "description_html": "<p>A new application.</p>",
    "slug": "teen-patti-octro",
    "id": "t1ocq5iar",
    "canonical_url": "",
    "seo_description": "",
    "release_notes": "",
    "link_configured": true,
    "seo_title": "",
    "seo_keywords": "",
    "name": "Teen Patti Octro",
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "is_coming_soon": true,
    "is_new": true,
    "serial_number": 34,
    "file_size": "90",
    "category": "Card",
    "rating": 4.2,
    "safety_status": "Verified",
    "developer": "Unknown ",
    "version": "3",
    "is_featured": false,
    "features_html": "",
    "publish_date": "2026-06-10T12:00:00.000Z",
    "faqs": [],
    "red_box_msg": "",
    "screenshots": [],
    "yellow_box_msg": "",
    "target_region": "",
    "video_url": "",
    "icon_url": "https://kk19a1nwwx.ucarecd.net/091fdebe-1562-41c6-99ea-b60665adb5ee/-/preview/512x512/",
    "custom_admin_box_html": "",
    "idea_box_msg": ""
  },
  {
    "link_configured": true,
    "seo_title": "",
    "seo_keywords": "",
    "canonical_url": "",
    "seo_description": "",
    "id": "rrmv44n9n",
    "slug": "zynga-poker-texas-holdem-game",
    "description_html": "<p>A new application.</p>",
    "created_at": "2026-06-03T10:30:01.393Z",
    "release_notes": "",
    "serial_number": 29,
    "file_size": "Unknown",
    "is_new": false,
    "developer": "Admin",
    "safety_status": "Verified",
    "rating": 5,
    "category": "Card",
    "name": "Zynga Poker- Texas Holdem Game",
    "is_coming_soon": true,
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "faqs": [],
    "red_box_msg": "",
    "yellow_box_msg": "",
    "screenshots": [],
    "is_featured": false,
    "version": "1.0",
    "features_html": "",
    "custom_admin_box_html": "",
    "icon_url": "https://kk19a1nwwx.ucarecd.net/5b72cf8f-4959-426e-9e1d-8e2150529efb/-/preview/240x240/",
    "idea_box_msg": "",
    "target_region": "",
    "video_url": ""
  },
  {
    "custom_admin_box_html": null,
    "icon_url": "https://1ewg1yyass.ucarecd.net/c0172402-c854-4016-876e-6b7769547c8f/-/preview/238x211/",
    "idea_box_msg": null,
    "target_region": "",
    "red_box_msg": null,
    "faqs": [],
    "yellow_box_msg": null,
    "screenshots": [],
    "version": "1.0",
    "is_featured": false,
    "features_html": null,
    "serial_number": 30,
    "file_size": "Unknown",
    "is_new": true,
    "developer": "Admin",
    "category": "Card",
    "rating": 5,
    "safety_status": "Verified",
    "name": "UNO! ",
    "is_coming_soon": true,
    "og_image_url": "",
    "custom_admin_box_heading": null,
    "seo_title": "",
    "link_configured": true,
    "seo_keywords": "",
    "slug": "uno-",
    "description_html": "<p>A new application.</p>",
    "id": "wf59smk6l",
    "seo_description": "",
    "canonical_url": "",
    "created_at": "2026-06-07T10:14:11.138Z",
    "release_notes": ""
  },
  {
    "developer": "Admin",
    "category": "Card",
    "rating": 5,
    "safety_status": "Verified",
    "serial_number": 31,
    "file_size": "Unknown",
    "is_new": false,
    "is_coming_soon": true,
    "og_image_url": "",
    "custom_admin_box_heading": "",
    "name": "Rummy GOLD - With Fast Rummy",
    "seo_keywords": "",
    "seo_title": "",
    "link_configured": true,
    "release_notes": "",
    "id": "8epj9jjpu",
    "description_html": "<p>A new application.</p>",
    "slug": "rummy-gold-with-fast-rummy",
    "canonical_url": "",
    "seo_description": "",
    "created_at": "2026-06-07T10:16:45.949Z",
    "idea_box_msg": "",
    "custom_admin_box_html": "",
    "icon_url": "https://1ewg1yyass.ucarecd.net/33e0d4e8-6e41-4791-9e41-8d915a12e504/-/preview/447x447/",
    "target_region": "",
    "yellow_box_msg": "",
    "screenshots": [],
    "faqs": [],
    "red_box_msg": "",
    "version": "1.0",
    "is_featured": false
  },
  {
    "seo_keywords": "",
    "seo_title": "",
    "link_configured": true,
    "release_notes": "",
    "seo_description": "",
    "canonical_url": "",
    "id": "8jt0hokyo",
    "description_html": "<p>A new application.</p>",
    "slug": "indian-rummy-3-patti-card-game",
    "created_at": "2026-06-07T10:19:11.616Z",
    "developer": "Admin",
    "safety_status": "Verified",
    "rating": 5,
    "category": "Card",
    "serial_number": 32,
    "file_size": "Unknown",
    "is_new": true,
    "is_coming_soon": true,
    "og_image_url": "",
    "custom_admin_box_heading": null,
    "name": "Indian Rummy 3 Patti Card Game",
    "yellow_box_msg": null,
    "screenshots": [],
    "faqs": [],
    "red_box_msg": null,
    "features_html": null,
    "is_featured": false,
    "version": "1.0",
    "idea_box_msg": null,
    "custom_admin_box_html": null,
    "icon_url": "https://1ewg1yyass.ucarecd.net/2a4b59ef-16a3-4b14-bad3-1c3796af3492/-/preview/447x447/",
    "target_region": ""
  },
  {
    "seo_title": "",
    "link_configured": true,
    "seo_keywords": "",
    "created_at": "2026-06-07T13:13:11.211Z",
    "seo_description": "",
    "canonical_url": "",
    "slug": "lucky-spin-slots",
    "description_html": "<p>A new application.</p>",
    "id": "01x9h7nfb",
    "release_notes": "",
    "is_new": false,
    "serial_number": 33,
    "file_size": "Unknown",
    "safety_status": "Verified",
    "category": "Slots",
    "rating": 5,
    "developer": "Admin",
    "name": "Lucky Spin Slots",
    "og_image_url": "https://1ewg1yyass.ucarecd.net/0f918f11-b247-4b5a-9d26-d510dddffbfe/-/preview/447x447/",
    "custom_admin_box_heading": "",
    "is_coming_soon": true,
    "red_box_msg": "",
    "faqs": [],
    "screenshots": [],
    "yellow_box_msg": "",
    "is_featured": false,
    "version": "1.0",
    "publish_date": "2026-07-08T13:08:00.000Z",
    "features_html": "",
    "icon_url": "https://1ewg1yyass.ucarecd.net/0f918f11-b247-4b5a-9d26-d510dddffbfe/-/preview/447x447/",
    "custom_admin_box_html": "",
    "idea_box_msg": "",
    "target_region": ""
  },
  {
    "target_region": "",
    "video_url": "",
    "custom_admin_box_html": "",
    "icon_url": "https://1ewg1yyass.ucarecd.net/9d9339e0-77d4-418b-86f8-0a0e074c1d4e/-/preview/190x190/",
    "idea_box_msg": "",
    "is_featured": false,
    "version": "1.0",
    "publish_date": "2026-06-12T15:30:00.000Z",
    "features_html": "",
    "faqs": [],
    "red_box_msg": "",
    "screenshots": [],
    "yellow_box_msg": "",
    "name": "IND Club",
    "is_coming_soon": true,
    "custom_admin_box_heading": "",
    "og_image_url": "",
    "file_size": "76",
    "serial_number": 28,
    "is_new": false,
    "developer": "AB Arora",
    "safety_status": "Verified",
    "category": "Yono",
    "rating": 4.5,
    "canonical_url": "",
    "seo_description": "",
    "id": "3cflt97b5",
    "description_html": "<p>A new application.</p>",
    "slug": "ind-club",
    "created_at": "2026-06-12T12:39:30.407Z",
    "release_notes": "",
    "link_configured": true,
    "seo_title": "",
    "seo_keywords": ""
  }
];

export const saveMockApps = (apps: AppConfig[]) => {
  try {
    localStorage.setItem('rummystore_apps', JSON.stringify(apps));
  } catch (e) {
    console.warn('saveMockApps storage failed:', e);
  }
  mockApps.splice(0, mockApps.length, ...apps);
};

export const mockSettings: GlobalSettings = {
  "disclaimer_heading": "DISCLAIMER ",
  "support_email": "support@rummyapp.online",
  "last_updated": "2026-07-19T02:06:04.833Z",
  "ethics_discrimination_text": "<div ",
  "meta_description": "Ok ",
  "seo_keywords": "M",
  "portal_heading": "IMPORTANT NOTICE ",
  "important_notice_heading": "VERY IMPORTANT NOTICE ",
  "logo_url": "https://y4q7avawns.ucarecd.net/b391a2fa-42f7-4b3a-a0d5-605cb22aead4/-/preview/1000x1000/",
  "banners": [
    {
      "link": "/",
      "image": "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
      "id": "mgg408of3",
      "subtitle": "Subtitle text",
      "title": "New Banner"
    }
  ],
  "hero_title_visible": true,
  "ticker_text": "LIVE: Unbiased words. Uncompromised truth. RummyApp Online  delivers pure transparency through independent reviews. ✒️",
  "disclaimer_text": "<div ",
  "hero_title_subtitle": "Step into the world of Rummy - compete, challenge friends, and rise to the top on RummyApp Online!",
  "helpline_telegram": "https://t.me/+d_B",
  "quick_links": [],
  "secure_index_subtitle": "The Ultimate Registry for Strategic Card Simulation, Arcade Logic, and Premium Virtual Gameplay Guides",
  "responsibility_content": "<!-- ",
  "hero_title_animation": "slide-up",
  "hero_title_style": "mono",
  "site_title": "RummyDex ",
  "about_content": "<!-- SA",
  "contact_content": "<p>Have questions or feedback? We'd love to hear from you. Our team typically responds within 24-48 hours.</p>",
  "privacy_content": "<!-- ",
  "social_links": {
    "linkedin": "",
    "youtube": "",
    "instagram": "",
    "twitter": "",
    "facebook": ""
  },
  "secure_index_title": "RummyDex ",
  "hero_title_color": "neon-sky",
  "terms_content": "<!-- ",
  "animations_enabled": true,
  "categories": [
    "Yono",
    "Card",
    "Slots"
  ],
  "ethics_heading": "ETHNICS",
  "trending_searches": [
    "RummyApp Online",
    "rummyapp.online",
    "rummyapp",
    "rummy app online review",
    "official rummy app online",
    "go rummy",
    "rummy store application reviews",
    "online gaming facts 2026",
    "gaming blogs india",
    "safe platform gaming",
    "top tier gaming experience",
    "digital entertainment portal",
    "guest play card games",
    "anonymous gaming portal",
    "no login card games",
    "free practice gaming events",
    "Rummy 91 review",
    "Rummy 91 casual app",
    "Rummy 91 game interface",
    "Rummy 91 virtual bonus",
    "play Rummy 91 online",
    "Gogo Rummy app",
    "Gogo Rummy game",
    "Gogo Rummy online",
    "Gogo Rummy review",
    "Gogo Rummy features",
    "Gogo Rummy interface",
    "Gogo Rummy guest mode",
    "Club INR app",
    "Club INR game",
    "Club INR online",
    "Club INR play",
    "Club INR review",
    "Club INR features",
    "Club INR guest mode",
    "ABC Rummy app",
    "ABC Rummy game",
    "ABC Rummy online",
    "ABC Rummy review",
    "ABC Rummy features",
    "ABC Rummy guest mode",
    "777 Rummy app",
    "777 Rummy online",
    "777 Rummy play",
    "777 Rummy review",
    "777 Rummy features",
    "777 Rummy guest mode",
    "Ever 777 app",
    "Ever 777 game",
    "Ever 777 online",
    "Ever 777 play",
    "Ever 777 review",
    "Ever 777 features",
    "Game Rummy app",
    "Game Rummy game",
    "Game Rummy online",
    "Game Rummy review",
    "Game Rummy features",
    "Hi Rummy app",
    "Hi Rummy game",
    "Hi Rummy online",
    "Hi Rummy play",
    "Hi Rummy review",
    "Hi Rummy features",
    "INR Rummy app",
    "INR Rummy game",
    "INR Rummy online",
    "INR Rummy play",
    "INR Rummy review",
    "INR Rummy features",
    "Jaiho Rummy app",
    "Jaiho Rummy game",
    "Jaiho Rummy online",
    "Jaiho Rummy play",
    "Jaiho Rummy review",
    "Love Rummy app",
    "Love Rummy game",
    "Love Rummy online",
    "Love Rummy play",
    "Love Rummy review",
    "Joy Rummy app",
    "Joy Rummy game",
    "Joy Rummy online",
    "Joy Rummy play",
    "Joy Rummy review",
    "Maha Games app",
    "Maha Games game",
    "Maha Games online",
    "Maha Games play",
    "Maha Games review",
    "Rummy Lodo app",
    "Rummy Lodo game",
    "Rummy Lodo online",
    "Rummy Lodo play",
    "Rummy Lodo review",
    "Rummy 77 app",
    "Rummy 77 game",
    "Rummy 77 online",
    "Rummy 77 play",
    "Rummy 77 review",
    "Share Slots app",
    "Share Slots game",
    "Share Slots online",
    "Share Slots play",
    "Share Slots review",
    "567 Slots app",
    "567 Slots game",
    "567 Slots online",
    "567 Slots play",
    "567 Slots review",
    "789 Jackpots app",
    "789 Jackpots game",
    "789 Jackpots online",
    "789 Jackpots play",
    "789 Jackpots review",
    "Yono VIP app",
    "Yono VIP game",
    "Yono VIP online",
    "Yono VIP play",
    "Yono VIP review",
    "yono games alternative",
    "indian rummy variations",
    "13 card rummy strategy",
    "pure sequence logic",
    "pure sequence guide",
    "joker card casual rules",
    "points rummy logic rules",
    "pool rummy strategy",
    "deals rummy tips",
    "drop point logic rules",
    "advanced rummy tactics",
    "beginner rummy tutorial",
    "real skill rummy simulation",
    "virtual skill rummy portal",
    "smooth card sorting",
    "lag free rummy gaming",
    "digital rummy table",
    "virtual gaming wallet",
    "premium strategy rummy platform",
    "drop rules in rummy",
    "skill based gaming portal",
    "lucky casual slot games"
  ],
  "important_notice": "<div ",
  "hero_title_text": "RummyApp Online ",
  "website_faqs": [],
  "helpline_whatsapp": "+918653034735",
  "favicon_url": "https://y4q7avawns.ucarecd.net/b391a2fa-42f7-4b3a-a0d5-605cb22aead4/-/preview/1000x1000/"
};

export const saveMockSettings = (settings: GlobalSettings) => {
  try {
    localStorage.setItem('rummystore_settings', JSON.stringify(settings));
  } catch (e) {
    console.warn('saveMockSettings storage failed:', e);
  }
  Object.assign(mockSettings, settings);
};

export const mockNews: NewsItem[] = [
  {
    "link": "Yirkgd",
    "ceo_description": "CEO Description",
    "ceo_name": "CEO Nameug",
    "content": "Detailed markdown content hehfkgsjtstkdjtsnfsjfzjfsjfsfjsre...",
    "author": "Admin",
    "seo_keywords": "",
    "seo_title": "News SEO Titlegdgd",
    "logo_url": "",
    "description": "News description...ydyldkgsitsjfahdau",
    "description_html": "<p>News HTML...</p>",
    "slug": "new-news",
    "id": "876hijgbk",
    "seo_description": "News SEO Meta Description",
    "canonical_url": "",
    "title": "Suhan",
    "category": "Ufuf",
    "read_time": "2 min",
    "tags": [],
    "og_image_url": "",
    "date": "2026-07-20T14:07:40.082Z",
    "target_region": "Global"
  }
];

export const saveMockNews = (newsList: NewsItem[]) => {
  try {
    localStorage.setItem('rummystore_news', JSON.stringify(newsList));
  } catch (e) {
    console.warn('saveMockNews storage failed:', e);
  }
  mockNews.splice(0, mockNews.length, ...newsList);
};

export const mockBlogs: BlogPost[] = [];

export const saveMockBlogs = (blogs: BlogPost[]) => {
  try {
    localStorage.setItem('rummystore_blogs', JSON.stringify(blogs));
  } catch (e) {
    console.warn('saveMockBlogs storage failed:', e);
  }
  mockBlogs.splice(0, mockBlogs.length, ...blogs);
};

export const mockVideos: VideoItem[] = [
  {
    "title": "RummyApp Online ",
    "created_at": "2026-05-22T12:22:35.244Z",
    "seo_description": "",
    "seo_title": "Rummy ",
    "slug": "",
    "id": "1",
    "youtube_url": "https://youtu.be/0uPeAuXIRdQ?si=aP9WFCyYCHKW2z5F",
    "description": "Looking for the best UI SMOOTH experience rummy "
  },
  {
    "seo_keywords": "",
    "youtube_url": "",
    "seo_title": "",
    "description": "",
    "seo_description": "",
    "slug": "",
    "id": "73jeeqtsr",
    "title": "",
    "created_at": "2026-05-29T14:26:28.226Z"
  }
];

export const saveMockVideos = (videos: VideoItem[]) => {
  try {
    localStorage.setItem('rummystore_videos', JSON.stringify(videos));
  } catch (e) {
    console.warn('saveMockVideos storage failed:', e);
  }
  mockVideos.splice(0, mockVideos.length, ...videos);
};
